import { TabooCard } from './types'

export const CARDS: TabooCard[] = [
  { category: 'Cucina', answer: 'PIZZA', taboos: ['impasto', 'fetta', 'forno a legna', 'margherita'] },
  { category: 'Cucina', answer: 'PASTA', taboos: ['semola', 'condimento', 'formato', 'al dente'] },
  { category: 'Cucina', answer: 'GELATO', taboos: ['coppetta', 'mantecatura', 'freddo', 'cono'] },
  { category: 'Cucina', answer: 'TIRAMISU', taboos: ['mascarpone', 'savoiardi', 'caffe', 'strati'] },
  { category: 'Animali', answer: 'CANE', taboos: ['muso', 'guinzaglio', 'abbaio', 'razza'] },
  { category: 'Animali', answer: 'GATTO', taboos: ['fusa', 'coda', 'micio', 'graffio'] },
  { category: 'Animali', answer: 'LEONE', taboos: ['criniera', 'branco', 'ruggito', 'savana'] },
  { category: 'Animali', answer: 'PANDA', taboos: ['bambu', 'sichuan', 'bianco e nero', 'orso'] },
  { category: 'Oggetti', answer: 'TELECOMANDO', taboos: ['infrarossi', 'tv', 'pile', 'canale'] },
  { category: 'Oggetti', answer: 'FRIGORIFERO', taboos: ['compressore', 'freddo', 'sportello', 'congelatore'] },
  { category: 'Oggetti', answer: 'ASTUCCIO', taboos: ['zip', 'penne', 'matite', 'scuola'] },
  { category: 'Oggetti', answer: 'ZAINO', taboos: ['spallacci', 'schiena', 'scomparti', 'viaggio'] },
  { category: 'Film', answer: 'TITANIC', taboos: ['iceberg', 'transatlantico', 'rose', 'cameron'] },
  { category: 'Film', answer: 'AVATAR', taboos: ['pandora', 'na vi', 'blu', 'effetti speciali'] },
  { category: 'Film', answer: 'JOKER', taboos: ['comic', 'risata', 'gotham', 'batman'] },
  { category: 'Film', answer: 'SHREK', taboos: ['palude', 'orco', 'fiona', 'animazione'] },
  { category: 'Sport', answer: 'CALCIO', taboos: ['fuorigioco', 'porta', 'rigore', 'pallone'] },
  { category: 'Sport', answer: 'TENNIS', taboos: ['campo in terra battuta', 'ace', 'rete', 'racchetta'] },
  { category: 'Sport', answer: 'BOXE', taboos: ['ring', 'guantoni', 'jab', 'pugni'] },
  { category: 'Sport', answer: 'NUOTO', taboos: ['corsia', 'vasca', 'stile libero', 'acqua'] },
  { category: 'Tecnologia', answer: 'SMARTPHONE', taboos: ['app', 'touch', 'notifiche', 'telefono'] },
  { category: 'Tecnologia', answer: 'COMPUTER', taboos: ['processore', 'tastiera', 'schermo', 'mouse'] },
  { category: 'Tecnologia', answer: 'INTERNET', taboos: ['browser', 'rete', 'connessione', 'online'] },
  { category: 'Tecnologia', answer: 'WHATSAPP', taboos: ['chat', 'messaggi', 'gruppi', 'verde'] },
  { category: 'Musica', answer: 'CHITARRA', taboos: ['corde', 'plettro', 'acustica', 'riff'] },
  { category: 'Musica', answer: 'PIANOFORTE', taboos: ['tasti', 'coda', 'melodia', 'classico'] },
  { category: 'Musica', answer: 'MICROFONO', taboos: ['voce', 'cantare', 'amplificare', 'palco'] },
  { category: 'Musica', answer: 'SANREMO', taboos: ['festival', 'cantanti', 'musica', 'televisione'] },
  { category: 'Viaggi', answer: 'AEROPORTO', taboos: ['voli', 'gate', 'bagagli', 'pista'] },
  { category: 'Viaggi', answer: 'VALIGIA', taboos: ['manico', 'ruote', 'bagagli', 'chiusura'] },
  { category: 'Viaggi', answer: 'VENEZIA', taboos: ['canali', 'gondola', 'laguna', 'ponti'] },
  { category: 'Viaggi', answer: 'PARIGI', taboos: ['eiffel', 'louvre', 'seine', 'capitale'] },
  { category: 'Casa', answer: 'LAMPADA', taboos: ['luce', 'bulbo', 'scrivania', 'abatjour'] },
  { category: 'Casa', answer: 'DIVANO', taboos: ['salotto', 'cuscino', 'comodita', 'poltrona'] },
  { category: 'Scuola', answer: 'QUADERNO', taboos: ['pagina', 'appunti', 'matita', 'lezione'] },
  { category: 'Trasporti', answer: 'TRENO', taboos: ['binario', 'stazione', 'rotaie', 'vagone'] },
  { category: 'Natura', answer: 'TEMPORALE', taboos: ['pioggia', 'fulmine', 'tuono', 'cielo'] },
  { category: 'Feste', answer: 'CAPODANNO', taboos: ['anno', 'brindisi', 'mezzanotte', 'fuochi'] },
  { category: 'Tecnologia', answer: 'TABLET', taboos: ['schermo', 'touch', 'app', 'portatile'] },
  { category: 'Cibo', answer: 'HAMBURGER', taboos: ['panino', 'carne', 'fast food', 'patatine'] },
  { category: 'Musica', answer: 'BATTERIA', taboos: ['tamburi', 'ritmo', 'bacchette', 'percussioni'] },
  { category: 'Sport', answer: 'PATTINAGGIO', taboos: ['ghiaccio', 'scivolare', 'lame', 'pista'] },
  { category: 'Casa', answer: 'TAVOLO', taboos: ['sedie', 'mangiare', 'legno', 'pranzo'] },
  { category: 'Casa', answer: 'SEDIA', taboos: ['sedersi', 'gambe', 'schienale', 'arredo'] },
  { category: 'Casa', answer: 'ARMADIO', taboos: ['vestiti', 'porta', 'camera', 'guardaroba'] },
  { category: 'Casa', answer: 'SPECCHIO', taboos: ['riflesso', 'bagno', 'immagine', 'vetro'] },
  { category: 'Oggetti', answer: 'OROLOGIO', taboos: ['tempo', 'ore', 'polso', 'minuti'] },
  { category: 'Oggetti', answer: 'OCCHIALI', taboos: ['vista', 'lenti', 'naso', 'montatura'] },
  { category: 'Oggetti', answer: 'OMBRELLO', taboos: ['pioggia', 'aprire', 'gocce', 'vento'] },
  { category: 'Oggetti', answer: 'CUSCINO', taboos: ['letto', 'testa', 'morbido', 'sonno'] },
  { category: 'Oggetti', answer: 'SCARPE', taboos: ['piedi', 'camminare', 'lacci', 'suola'] },
  { category: 'Cibo', answer: 'BISCOTTO', taboos: ['colazione', 'dolce', 'latte', 'forno'] },
  { category: 'Cibo', answer: 'PANINO', taboos: ['pane', 'ripieno', 'pranzo', 'merenda'] },
  { category: 'Cibo', answer: 'INSALATA', taboos: ['verdure', 'leggera', 'olio', 'lattuga'] },
  { category: 'Cibo', answer: 'CIOCCOLATO', taboos: ['cacao', 'dolce', 'tavoletta', 'nero'] },
  { category: 'Trasporti', answer: 'AUTOBUS', taboos: ['fermata', 'ruote', 'biglietto', 'sedili'] },
  { category: 'Trasporti', answer: 'METRO', taboos: ['sottoterra', 'binari', 'stazioni', 'linee'] },
  { category: 'Trasporti', answer: 'BICICLETTA', taboos: ['pedali', 'ruote', 'catena', 'casco'] },
  { category: 'Natura', answer: 'MONTAGNA', taboos: ['vetta', 'salita', 'valle', 'neve'] },
  { category: 'Natura', answer: 'FIUME', taboos: ['acqua', 'sponde', 'corrente', 'ponte'] },
  { category: 'Natura', answer: 'SOLE', taboos: ['caldo', 'giorno', 'luce', 'estate'] },
  { category: 'Casa', answer: 'CUSCINO', taboos: ['letto', 'testa', 'morbido', 'sonno'] },
  { category: 'Casa', answer: 'COPERTA', taboos: ['caldo', 'letto', 'lana', 'notte'] },
  { category: 'Casa', answer: 'SPECCHIO', taboos: ['riflesso', 'bagno', 'immagine', 'vetro'] },
  { category: 'Casa', answer: 'ARMADIO', taboos: ['vestiti', 'porta', 'guardaroba', 'camera'] },
  { category: 'Casa', answer: 'LAMPADA', taboos: ['luce', 'bulbo', 'abatjour', 'scrivania'] },
  { category: 'Tecnologia', answer: 'TABLET', taboos: ['schermo', 'touch', 'app', 'portatile'] },
  { category: 'Tecnologia', answer: 'AURICOLARI', taboos: ['orecchie', 'musica', 'cavo', 'ascolto'] },
  { category: 'Tecnologia', answer: 'WEBCAM', taboos: ['video', 'pc', 'chiamata', 'camera'] },
  { category: 'Tecnologia', answer: 'POWERBANK', taboos: ['batteria', 'carica', 'telefono', 'energia'] },
  { category: 'Cibo', answer: 'PIADINA', taboos: ['impasto', 'ripieno', 'romagna', 'sottile'] },
  { category: 'Cibo', answer: 'LASAGNA', taboos: ['pasta', 'forno', 'ragu', 'strati'] },
  { category: 'Cibo', answer: 'PIZZA MARINARA', taboos: ['pomodoro', 'aglio', 'origano', 'senza mozzarella'] },
  { category: 'Cibo', answer: 'CROSTATA', taboos: ['frolla', 'marmellata', 'dolce', 'torta'] },
  { category: 'Musica', answer: 'VIOLINO', taboos: ['corde', 'archetto', 'classico', 'orchestra'] },
  { category: 'Musica', answer: 'SAX', taboos: ['jazz', 'fiato', 'ottone', 'strumento'] },
  { category: 'Musica', answer: 'BASSO', taboos: ['corde', 'ritmo', 'gruppo', 'suono'] },
  { category: 'Musica', answer: 'CANTANTE', taboos: ['voce', 'microfono', 'palco', 'brano'] },
  { category: 'Sport', answer: 'BASKET', taboos: ['canestro', 'palla', 'campo', 'squadra'] },
  { category: 'Sport', answer: 'CALCETTO', taboos: ['campo', 'squadre', 'amici', 'pallone'] },
  { category: 'Sport', answer: 'SCI', taboos: ['neve', 'piste', 'discesa', 'montagna'] },
  { category: 'Sport', answer: 'ARRAMPICATA', taboos: ['parete', 'corda', 'salita', 'roccia'] },
  { category: 'Viaggi', answer: 'HOTEL', taboos: ['camera', 'vacanze', 'letto', 'reception'] },
  { category: 'Viaggi', answer: 'MARE', taboos: ['spiaggia', 'acqua', 'onda', 'estate'] },
  { category: 'Viaggi', answer: 'MONTAGNA', taboos: ['vetta', 'salita', 'neve', 'alpeggio'] },
  { category: 'Viaggi', answer: 'PAESE', taboos: ['villaggio', 'campagna', 'case', 'strada'] },
  { category: 'Natura', answer: 'TEMPORALE', taboos: ['fulmine', 'tuono', 'pioggia', 'nuvola'] },
  { category: 'Natura', answer: 'ARCOBALENO', taboos: ['pioggia', 'colori', 'cielo', 'sole'] },
  { category: 'Natura', answer: 'FORESTA', taboos: ['alberi', 'verde', 'natura', 'bosco'] },
  { category: 'Natura', answer: 'FIORE', taboos: ['petali', 'profumo', 'pianta', 'giardino'] },
]

function shuffleArray<T>(items: T[]): T[] {
  const copy = [...items]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

export function getShuffledCards(count = CARDS.length): TabooCard[] {
  return shuffleArray(CARDS)
    .slice(0, count)
    .map(card => ({
      ...card,
      taboos: shuffleArray(card.taboos) as TabooCard['taboos'],
    }))
}
