import { TabooCard } from './types'

export const CARDS: TabooCard[] = [
  { category: 'Cucina', answer: 'PIZZA', taboos: ['forno', 'pomodoro', 'mozzarella', 'margherita'] },
  { category: 'Cucina', answer: 'PASTA', taboos: ['spaghetti', 'primo', 'ragu', 'italia'] },
  { category: 'Cucina', answer: 'GELATO', taboos: ['freddo', 'cono', 'estate', 'dolce'] },
  { category: 'Cucina', answer: 'TIRAMISU', taboos: ['caffe', 'mascarpone', 'dolce', 'cucchiaio'] },
  { category: 'Animali', answer: 'CANE', taboos: ['abbaia', 'guinzaglio', 'cucciolo', 'fedele'] },
  { category: 'Animali', answer: 'GATTO', taboos: ['miagola', 'fusa', 'felino', 'micio'] },
  { category: 'Animali', answer: 'LEONE', taboos: ['criniera', 'giungla', 'ruggito', 're'] },
  { category: 'Animali', answer: 'PANDA', taboos: ['bambu', 'cina', 'orso', 'bianco'] },
  { category: 'Oggetti', answer: 'TELECOMANDO', taboos: ['tv', 'tasti', 'cambia', 'canale'] },
  { category: 'Oggetti', answer: 'FRIGORIFERO', taboos: ['freddo', 'cibo', 'cucina', 'sportello'] },
  { category: 'Oggetti', answer: 'ASTUCCIO', taboos: ['penne', 'scuola', 'matita', 'zip'] },
  { category: 'Oggetti', answer: 'ZAINO', taboos: ['spallacci', 'scuola', 'borsa', 'viaggio'] },
  { category: 'Film', answer: 'TITANIC', taboos: ['iceberg', 'nave', 'leo', 'rose'] },
  { category: 'Film', answer: 'AVATAR', taboos: ['navi', 'blu', 'pandora', 'sci-fi'] },
  { category: 'Film', answer: 'JOKER', taboos: ['batman', 'cattivo', 'risata', 'comic'] },
  { category: 'Film', answer: 'SHREK', taboos: ['orco', 'palude', 'fiona', 'verde'] },
  { category: 'Sport', answer: 'CALCIO', taboos: ['pallone', 'porta', 'goal', 'campo'] },
  { category: 'Sport', answer: 'TENNIS', taboos: ['racchetta', 'campo', 'rete', 'pallina'] },
  { category: 'Sport', answer: 'BOXE', taboos: ['guantoni', 'ring', 'pugni', 'combattimento'] },
  { category: 'Sport', answer: 'NUOTO', taboos: ['acqua', 'corsia', 'vasca', 'stile'] },
  { category: 'Tecnologia', answer: 'SMARTPHONE', taboos: ['telefono', 'app', 'schermo', 'tocco'] },
  { category: 'Tecnologia', answer: 'COMPUTER', taboos: ['mouse', 'tastiera', 'pc', 'monitor'] },
  { category: 'Tecnologia', answer: 'INTERNET', taboos: ['web', 'rete', 'online', 'browser'] },
  { category: 'Tecnologia', answer: 'WHATSAPP', taboos: ['chat', 'messaggio', 'verde', 'telefonino'] },
  { category: 'Musica', answer: 'CHITARRA', taboos: ['corde', 'strumento', 'suonare', 'acustica'] },
  { category: 'Musica', answer: 'PIANOFORTE', taboos: ['tasti', 'note', 'coda', 'strumento'] },
  { category: 'Musica', answer: 'MICROFONO', taboos: ['voce', 'cantare', 'amplificare', 'palco'] },
  { category: 'Musica', answer: 'SANREMO', taboos: ['festival', 'cantanti', 'musica', 'televisione'] },
  { category: 'Viaggi', answer: 'AEROPORTO', taboos: ['voli', 'gate', 'bagagli', 'partenza'] },
  { category: 'Viaggi', answer: 'VALIGIA', taboos: ['viaggio', 'vestiti', 'ruote', 'vacanze'] },
  { category: 'Viaggi', answer: 'VENEZIA', taboos: ['canali', 'gondola', 'laguna', 'ponti'] },
  { category: 'Viaggi', answer: 'PARIGI', taboos: ['eiffel', 'francia', 'louvre', 'romantica'] },
  { category: 'Casa', answer: 'LAMPADA', taboos: ['luce', 'bulbo', 'scrivania', 'abatjour'] },
  { category: 'Casa', answer: 'DIVANO', taboos: ['salotto', 'cuscino', 'comodita', 'poltrona'] },
  { category: 'Scuola', answer: 'QUADERNO', taboos: ['pagina', 'appunti', 'matita', 'lezione'] },
  { category: 'Trasporti', answer: 'TRENO', taboos: ['binario', 'stazione', 'rotaie', 'vagone'] },
  { category: 'Natura', answer: 'TEMPORALE', taboos: ['pioggia', 'fulmine', 'tuono', 'cielo'] },
  { category: 'Feste', answer: 'CAPODANNO', taboos: ['anno', 'brindisi', 'mezzanotte', 'fuochi'] },
  { category: 'Tecnologia', answer: 'TABLET', taboos: ['schermo', 'touch', 'app', 'portatile'] },
  { category: 'Cibo', answer: 'HAMBURGER', taboos: ['panino', 'carne', 'fast food', 'patatine'] },
  { category: 'Musica', answer: 'BATTERIA', taboos: ['tamburi', 'ritmo', 'bacchette', 'percussioni'] },
  { category: 'Sport', answer: 'PATTINAGGIO', taboos: ['ghiaccio', 'scivolare', 'lame', 'pista'] },
  { category: 'Casa', answer: 'TAVOLO', taboos: ['sedie', 'mangiare', 'legno', 'pranzo'] },
  { category: 'Casa', answer: 'SEDIA', taboos: ['sedersi', 'gambe', 'schienale', 'arredo'] },
  { category: 'Casa', answer: 'ARMADIO', taboos: ['vestiti', 'porta', 'camera', 'guardaroba'] },
  { category: 'Casa', answer: 'SPECCHIO', taboos: ['riflesso', 'bagno', 'immagine', 'vetro'] },
  { category: 'Oggetti', answer: 'OROLOGIO', taboos: ['tempo', 'ore', 'polso', 'minuti'] },
  { category: 'Oggetti', answer: 'OCCHIALI', taboos: ['vista', 'lenti', 'naso', 'montatura'] },
  { category: 'Oggetti', answer: 'OMBRELLO', taboos: ['pioggia', 'aprire', 'gocce', 'vento'] },
  { category: 'Oggetti', answer: 'CUSCINO', taboos: ['letto', 'testa', 'morbido', 'sonno'] },
  { category: 'Oggetti', answer: 'SCARPE', taboos: ['piedi', 'camminare', 'lacci', 'suola'] },
  { category: 'Cibo', answer: 'BISCOTTO', taboos: ['colazione', 'dolce', 'latte', 'forno'] },
  { category: 'Cibo', answer: 'PANINO', taboos: ['pane', 'ripieno', 'pranzo', 'merenda'] },
  { category: 'Cibo', answer: 'INSALATA', taboos: ['verdure', 'leggera', 'olio', 'lattuga'] },
  { category: 'Cibo', answer: 'CIOCCOLATO', taboos: ['cacao', 'dolce', 'tavoletta', 'nero'] },
  { category: 'Trasporti', answer: 'AUTOBUS', taboos: ['fermata', 'ruote', 'biglietto', 'sedili'] },
  { category: 'Trasporti', answer: 'METRO', taboos: ['sottoterra', 'binari', 'stazioni', 'linee'] },
  { category: 'Trasporti', answer: 'BICICLETTA', taboos: ['pedali', 'ruote', 'catena', 'casco'] },
  { category: 'Natura', answer: 'MONTAGNA', taboos: ['vetta', 'salita', 'valle', 'neve'] },
  { category: 'Natura', answer: 'FIUME', taboos: ['acqua', 'sponde', 'corrente', 'ponte'] },
  { category: 'Natura', answer: 'SOLE', taboos: ['caldo', 'giorno', 'luce', 'estate'] },
  { category: 'Casa', answer: 'CUSCINO', taboos: ['letto', 'testa', 'morbido', 'sonno'] },
  { category: 'Casa', answer: 'COPERTA', taboos: ['caldo', 'letto', 'lana', 'notte'] },
  { category: 'Casa', answer: 'SPECCHIO', taboos: ['riflesso', 'bagno', 'immagine', 'vetro'] },
  { category: 'Casa', answer: 'ARMADIO', taboos: ['vestiti', 'porta', 'guardaroba', 'camera'] },
  { category: 'Casa', answer: 'LAMPADA', taboos: ['luce', 'bulbo', 'abatjour', 'scrivania'] },
  { category: 'Tecnologia', answer: 'TABLET', taboos: ['schermo', 'touch', 'app', 'portatile'] },
  { category: 'Tecnologia', answer: 'AURICOLARI', taboos: ['orecchie', 'musica', 'cavo', 'ascolto'] },
  { category: 'Tecnologia', answer: 'WEBCAM', taboos: ['video', 'pc', 'chiamata', 'camera'] },
  { category: 'Tecnologia', answer: 'POWERBANK', taboos: ['batteria', 'carica', 'telefono', 'energia'] },
  { category: 'Cibo', answer: 'PIADINA', taboos: ['impasto', 'ripieno', 'romagna', 'sottile'] },
  { category: 'Cibo', answer: 'LASAGNA', taboos: ['pasta', 'forno', 'ragu', 'strati'] },
  { category: 'Cibo', answer: 'PIZZA MARINARA', taboos: ['pomodoro', 'aglio', 'origano', 'senza mozzarella'] },
  { category: 'Cibo', answer: 'CROSTATA', taboos: ['frolla', 'marmellata', 'dolce', 'torta'] },
  { category: 'Musica', answer: 'VIOLINO', taboos: ['corde', 'archetto', 'classico', 'orchestra'] },
  { category: 'Musica', answer: 'SAX', taboos: ['jazz', 'fiato', 'ottone', 'strumento'] },
  { category: 'Musica', answer: 'BASSO', taboos: ['corde', 'ritmo', 'gruppo', 'suono'] },
  { category: 'Musica', answer: 'CANTANTE', taboos: ['voce', 'microfono', 'palco', 'brano'] },
  { category: 'Sport', answer: 'BASKET', taboos: ['canestro', 'palla', 'campo', 'squadra'] },
  { category: 'Sport', answer: 'CALCETTO', taboos: ['campo', 'squadre', 'amici', 'pallone'] },
  { category: 'Sport', answer: 'SCI', taboos: ['neve', 'piste', 'discesa', 'montagna'] },
  { category: 'Sport', answer: 'ARRAMPICATA', taboos: ['parete', 'corda', 'salita', 'roccia'] },
  { category: 'Viaggi', answer: 'HOTEL', taboos: ['camera', 'vacanze', 'letto', 'reception'] },
  { category: 'Viaggi', answer: 'MARE', taboos: ['spiaggia', 'acqua', 'onda', 'estate'] },
  { category: 'Viaggi', answer: 'MONTAGNA', taboos: ['vetta', 'salita', 'neve', 'alpeggio'] },
  { category: 'Viaggi', answer: 'PAESE', taboos: ['villaggio', 'campagna', 'case', 'strada'] },
  { category: 'Natura', answer: 'TEMPORALE', taboos: ['fulmine', 'tuono', 'pioggia', 'nuvola'] },
  { category: 'Natura', answer: 'ARCOBALENO', taboos: ['pioggia', 'colori', 'cielo', 'sole'] },
  { category: 'Natura', answer: 'FORESTA', taboos: ['alberi', 'verde', 'natura', 'bosco'] },
  { category: 'Natura', answer: 'FIORE', taboos: ['petali', 'profumo', 'pianta', 'giardino'] },
]

function shuffleArray<T>(items: T[]): T[] {
  const copy = [...items]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

export function getShuffledCards(count = CARDS.length): TabooCard[] {
  return shuffleArray(CARDS)
    .slice(0, count)
    .map(card => ({
      ...card,
      taboos: shuffleArray(card.taboos) as TabooCard['taboos'],
    }))
}
