import { CompletamentoQuestion } from './types'

export const QUESTIONS: CompletamentoQuestion[] = [
  // --- ANIMALI ---
  { clue: 'Animale che abbaia', answer: 'CANE' },
  { clue: 'Frutto giallo ricurvo', answer: 'BANANA' },
  { clue: 'Pianeta rosso', answer: 'MARTE' },
  { clue: 'Animale a righe bianche e nere', answer: 'ZEBRA' },
  { clue: 'Il re della giungla', answer: 'LEONE' },
  { clue: 'Animale con la proboscide', answer: 'ELEFANTE' },
  { clue: 'Animale marino con tentacoli', answer: 'POLPO' },
  { clue: 'Animale marsupiale australiano', answer: 'CANGURO' },
  { clue: 'Felino maculato velocissimo', answer: 'GHEPARDO' },
  { clue: 'Rettile che cambia colore', answer: 'CAMALEONTE' },
  { clue: 'Uccello tropicale coloratissimo che parla', answer: 'PAPPAGALLO' },
  { clue: 'Animale con le pinne e un grande dente', answer: 'NARVALO' },
  { clue: 'Animale del bambù in Cina', answer: 'PANDA' },
  { clue: 'Insetto che produce miele', answer: 'APE' },
  { clue: 'Grande scimmia africana', answer: 'GORILLA' },
  { clue: 'Animale col guscio duro sulla schiena', answer: 'TARTARUGA' },
  { clue: 'Felino con la criniera', answer: 'LEONE' },
  { clue: 'Rettile più lungo del mondo', answer: 'ANACONDA' },
  { clue: 'Uccello polare che non vola', answer: 'PINGUINO' },
  { clue: 'Predatore del mare bianco e grigio', answer: 'SQUALO' },
  { clue: 'Mammifero marino con l\'eco', answer: 'DELFINO' },
  { clue: 'Il più grande carnivoro terrestre', answer: 'ORSO' },
  { clue: 'Animale notturno con le ali di membrana', answer: 'PIPISTRELLO' },
  { clue: 'Animale con le strisce sulla schiena che scava', answer: 'TASSO' },
  { clue: 'Uccello rapace notturno', answer: 'GUFO' },
  { clue: 'Rettile con collo lunghissimo', answer: 'GIRAFFA' },
  { clue: 'Animale con due gobbe nel deserto', answer: 'CAMMELLO' },
  { clue: 'Mammifero semi-acquatico con la coda piatta', answer: 'CASTORO' },
  { clue: 'Grande felino delle nevi dell\'Himalaya', answer: 'LEOPARDO' },
  { clue: 'Uccello più grande del mondo', answer: 'STRUZZO' },

  // --- CALCIO ---
  { clue: 'Chi difende la porta nel calcio', answer: 'PORTIERE' },
  { clue: 'Tiro dal dischetto nel calcio', answer: 'RIGORE' },
  { clue: 'Colore del cartellino grave nel calcio', answer: 'ROSSO' },
  { clue: 'Il calcio all\'angolo del campo', answer: 'CORNER' },
  { clue: 'Chi dirige la partita', answer: 'ARBITRO' },
  { clue: 'Il trofeo del campionato italiano', answer: 'SCUDETTO' },
  { clue: 'Leggenda della Roma, soprannominato "Il Capitano"', answer: 'TOTTI' },
  { clue: 'Il più grande calciatore argentino', answer: 'MESSI' },
  { clue: 'Portiere leggenda della Juventus', answer: 'BUFFON' },
  { clue: 'Calciatore soprannominato CR7', answer: 'RONALDO' },
  { clue: 'Il giovane fenomeno francese del PSG', answer: 'MBAPPE' },
  { clue: 'Il bomber norvegese del Manchester City', answer: 'HAALAND' },
  { clue: 'Competizione europea per club più importante', answer: 'CHAMPIONS' },
  { clue: 'Stadio della Juventus a Torino', answer: 'ALLIANZ' },
  { clue: 'Tecnica di superare l\'avversario col pallone', answer: 'DRIBBLING' },
  { clue: 'Passaggio che porta direttamente al gol', answer: 'ASSIST' },
  { clue: 'Campionato italiano di calcio', answer: 'SERIA' },
  { clue: 'Il nome dello stadio di Milan e Inter', answer: 'SANSIRO' },
  { clue: 'Fuorigioco in inglese nel calcio', answer: 'OFFSIDE' },
  { clue: 'Gol segnato di testa', answer: 'COLPODTESTA' },

  // --- SPORT ---
  { clue: 'Sport con racchetta e pallina gialla', answer: 'TENNIS' },
  { clue: 'Sport di velocità su quattro ruote con pit stop', answer: 'FORMULA' },
  { clue: 'Sport motociclistico su pista', answer: 'MOTOGP' },
  { clue: 'Sport olimpico di velocità in acqua', answer: 'NUOTO' },
  { clue: 'Gara podistica di 42 km', answer: 'MARATONA' },
  { clue: 'Sport con casco, guantoni e ring', answer: 'BOXE' },
  { clue: 'Sport invernale sulle piste di neve', answer: 'SCI' },
  { clue: 'Sport con il canestro e la palla arancione', answer: 'BASKET' },
  { clue: 'Sport con rete alta e 6 giocatori per lato', answer: 'PALLAVOLO' },
  { clue: 'Sport inglese con uomini in maglia a righe', answer: 'RUGBY' },
  { clue: 'Atleta più veloce della storia', answer: 'BOLT' },
  { clue: 'Il numero uno del tennis mondiale per anni', answer: 'FEDERER' },
  { clue: 'Sport del "birdie" e del "par"', answer: 'GOLF' },
  { clue: 'Sport con bacchette e tamburo', answer: 'BATTERIA' },
  { clue: 'Gara ciclistica più famosa d\'Italia', answer: 'GIRO' },
  { clue: 'Sport con spada e maschera', answer: 'SCHERMA' },
  { clue: 'Pilota di F1 con più titoli mondiali', answer: 'HAMILTON' },
  { clue: 'Campione italiano di MotoGP soprannominato "il Dottore"', answer: 'ROSSI' },

  // --- MUSICA ---
  { clue: 'Strumento a corde pizzicate con 6 corde', answer: 'CHITARRA' },
  { clue: 'Strumento a 88 tasti bianchi e neri', answer: 'PIANOFORTE' },
  { clue: 'Frontman dei Queen', answer: 'MERCURY' },
  { clue: 'Gruppo musicale di Liverpool degli anni 60', answer: 'BEATLES' },
  { clue: 'Re del pop americano morto nel 2009', answer: 'JACKSON' },
  { clue: 'Festival musicale più importante d\'Italia', answer: 'SANREMO' },
  { clue: 'Cantante italiano soprannominato il Blasco', answer: 'VASCO' },
  { clue: 'Strumento a fiato del jazz per eccellenza', answer: 'SASSOFONO' },
  { clue: 'Strumento a percussione della batteria', answer: 'RULLANTE' },
  { clue: 'Cantante di "Shape of You"', answer: 'SHEERAN' },
  { clue: 'La cantante di "Poker Face"', answer: 'GAGA' },
  { clue: 'Genere musicale nato nei ghetti americani', answer: 'RAP' },
  { clue: 'Genere musicale elettronico da discoteca', answer: 'TECHNO' },
  { clue: 'Il re del rock americano degli anni 50', answer: 'ELVIS' },
  { clue: 'Cantante italiano di "Grande" e "Rolls Royce"', answer: 'TIZIANO' },
  { clue: 'La voce degli U2', answer: 'BONO' },
  { clue: 'Strumento musicale a corde dell\'orchestra', answer: 'VIOLINO' },
  { clue: 'Genere musicale brasiliano con maracas', answer: 'SAMBA' },

  // --- GEOGRAFIA ---
  { clue: 'La città con la Torre Eiffel', answer: 'PARIGI' },
  { clue: 'Capitale del Giappone', answer: 'TOKYO' },
  { clue: 'Il fiume più lungo del mondo', answer: 'NILO' },
  { clue: 'Il deserto più grande del mondo', answer: 'SAHARA' },
  { clue: 'La montagna più alta del mondo', answer: 'EVEREST' },
  { clue: 'Isola vulcanica a sud dell\'Italia', answer: 'SICILIA' },
  { clue: 'La cascata più alta del mondo', answer: 'ANGEL' },
  { clue: 'Il paese più piccolo del mondo', answer: 'VATICANO' },
  { clue: 'Il continente più freddo del mondo', answer: 'ANTARTIDE' },
  { clue: 'Capitale dell\'Australia', answer: 'CANBERRA' },
  { clue: 'Il vulcano attivo siciliano', answer: 'ETNA' },
  { clue: 'Il lago più grande del mondo', answer: 'CASPIO' },
  { clue: 'La capitale del Brasile', answer: 'BRASILIA' },
  { clue: 'Il paese delle mille isole nel sud-est asiatico', answer: 'INDONESIA' },
  { clue: 'La capitale della Germania', answer: 'BERLINO' },
  { clue: 'Il paese più grande del mondo', answer: 'RUSSIA' },
  { clue: 'Catena montuosa tra Italia e Francia', answer: 'ALPI' },
  { clue: 'Il mare che separa Italia dalla Grecia', answer: 'ADRIATICO' },
  { clue: 'Capitale dell\'Argentina', answer: 'BUENOSAIRES' },
  { clue: 'La foresta pluviale più grande del mondo', answer: 'AMAZZONIA' },

  // --- STORIA ---
  { clue: 'Il famoso combattente romano dell\'arena', answer: 'GLADIATORE' },
  { clue: 'Imperatore di Francia poi esiliato a Sant\'Elena', answer: 'NAPOLEONE' },
  { clue: 'Conquistatore dell\'America nel 1492', answer: 'COLOMBO' },
  { clue: 'Il re egizio, figlio di Dio del sole', answer: 'FARAONE' },
  { clue: 'L\'anfiteatro romano di Roma', answer: 'COLOSSEO' },
  { clue: 'Monumento funebre egizio a forma di triangolo', answer: 'PIRAMIDE' },
  { clue: 'Guerriero medievale a cavallo con armatura', answer: 'CAVALIERE' },
  { clue: 'Il leader comunista sovietico della WWII', answer: 'STALIN' },
  { clue: 'Il genio di Vinci pittore e inventore', answer: 'LEONARDO' },
  { clue: 'Il filosofo greco maestro di Alessandro Magno', answer: 'ARISTOTELE' },
  { clue: 'La rivoluzione del 1789 in Francia', answer: 'RIVOLUZIONE' },
  { clue: 'Il muro abbattuto nel 1989 a Berlino', answer: 'MURO' },
  { clue: 'Navigatore portoghese che circumnavigò il globo', answer: 'MAGELLANO' },
  { clue: 'Il primo uomo sulla Luna nel 1969', answer: 'ARMSTRONG' },
  { clue: 'Il condottiero greco che conquistò la Persia', answer: 'ALESSANDRO' },

  // --- MACCHINE E MOTO ---
  { clue: 'Marca italiana di supercar con il cavallino rampante', answer: 'FERRARI' },
  { clue: 'Marca italiana di supercar con il toro', answer: 'LAMBORGHINI' },
  { clue: 'Marca tedesca di auto con le quattro ruote', answer: 'BMW' },
  { clue: 'Marca americana di moto famose per il suono', answer: 'HARLEY' },
  { clue: 'Marca italiana di moto sportive', answer: 'DUCATI' },
  { clue: 'Auto elettrica del visionario Elon Musk', answer: 'TESLA' },
  { clue: 'Il campione di F1 che ha vinto 7 titoli', answer: 'SCHUMACHER' },
  { clue: 'La competizione motociclistica più importante', answer: 'MOTOGP' },
  { clue: 'Il pneumatico della moto o dell\'auto', answer: 'GOMMA' },
  { clue: 'La sosta in F1 per cambiare le gomme', answer: 'PITSTOP' },
  { clue: 'Marca giapponese di moto con la N', answer: 'NINJA' },
  { clue: 'Motore con due cilindri opposti', answer: 'BICILINDRICO' },
  { clue: 'La gara automobilistica più famosa del mondo a Monaco', answer: 'MONTECARLO' },
  { clue: 'Il campione olandese attuale di F1', answer: 'VERSTAPPEN' },

  // --- CIBO E CUCINA ---
  { clue: 'Pasta al sugo con uova e guanciale', answer: 'CARBONARA' },
  { clue: 'Dolce italiano al caffè con mascarpone', answer: 'TIRAMISU' },
  { clue: 'Primo piatto italiano a base di riso', answer: 'RISOTTO' },
  { clue: 'Dolce siciliano fritto con ricotta', answer: 'CANNOLO' },
  { clue: 'Piatto giapponese di riso e pesce crudo', answer: 'SUSHI' },
  { clue: 'La pasta più famosa di Napoli', answer: 'PIZZA' },
  { clue: 'Crema gelata italiana alla nocciola', answer: 'GELATO' },
  { clue: 'Formaggio duro padano grattugiato', answer: 'PARMIGIANO' },
  { clue: 'Salume rosa di Bologna', answer: 'MORTADELLA' },
  { clue: 'Bevanda alcolica italiana con Aperol', answer: 'SPRITZ' },
  { clue: 'Formaggio morbido bianco di bufala', answer: 'MOZZARELLA' },
  { clue: 'Pasta lunga più celebre al mondo', answer: 'SPAGHETTI' },
  { clue: 'Piatto messicano con tortilla', answer: 'TACOS' },
  { clue: 'Croissant in italiano', answer: 'CORNETTO' },
  { clue: 'La pasta al forno con besciamella', answer: 'LASAGNA' },

  // --- CULTURA GENERALE E DIVERTIMENTO ---
  { clue: 'Il social network delle foto fondato da Zuckerberg', answer: 'FACEBOOK' },
  { clue: 'La piattaforma di video più grande del mondo', answer: 'YOUTUBE' },
  { clue: 'Il film più costoso della storia - iceberg incluso', answer: 'TITANIC' },
  { clue: 'Il personaggio Marvel con lo scudo', answer: 'CAPITAN' },
  { clue: 'Il mago di Hogwarts con la cicatrice', answer: 'POTTER' },
  { clue: 'Il gioco da tavolo dove si comprano casette', answer: 'MONOPOLY' },
  { clue: 'Il gioco di carte italiano a 40 carte', answer: 'BRISCOLA' },
  { clue: 'La bevanda calda del mattino degli italiani', answer: 'CAFFE' },
  { clue: 'Il personaggio Disney con le orecchie tonde', answer: 'TOPOLINO' },
  { clue: 'Il film di James Cameron con i Na\'vi', answer: 'AVATAR' },
  { clue: 'La serie TV dei draghi e del Trono', answer: 'GAME' },
  { clue: 'Il cantante di "Thriller"', answer: 'JACKSON' },
  { clue: 'L\'attore di Iron Man', answer: 'DOWNEY' },
  { clue: 'Il gioco dei mattoncini colorati danese', answer: 'LEGO' },
  { clue: 'Il social delle storie che spariscono', answer: 'SNAPCHAT' },
]

export function getShuffledQuestions(count = 30): CompletamentoQuestion[] {
  return [...QUESTIONS].sort(() => Math.random() - 0.5).slice(0, count)
}
