import { CompletamentoQuestion } from './types'

export const QUESTIONS: CompletamentoQuestion[] = [
  { clue: 'Animale che abbaia', answer: 'CANE' },
  { clue: 'Frutto giallo ricurvo', answer: 'BANANA' },
  { clue: 'Pianeta rosso', answer: 'MARTE' },
  { clue: 'Colore del cielo sereno', answer: 'AZZURRO' },
  { clue: 'Animale a righe bianche e nere', answer: 'ZEBRA' },
  { clue: 'La città con il Colosseo', answer: 'ROMA' },
  { clue: 'Strumento a corde pizzicate', answer: 'CHITARRA' },
  { clue: 'Insetto che produce miele', answer: 'APE' },
  { clue: 'Frutto rosso con semi esterni', answer: 'FRAGOLA' },
  { clue: 'Veicolo su due ruote a pedali', answer: 'BICICLETTA' },
  { clue: 'Animale marino con tentacoli', answer: 'POLIPO' },
  { clue: 'Bevanda calda dalla Colombia', answer: 'CAFFE' },
  { clue: 'Il re della giungla', answer: 'LEONE' },
  { clue: 'Dispositivo portatile per chiamare', answer: 'TELEFONO' },
  { clue: 'Stagione con la neve', answer: 'INVERNO' },
  { clue: 'Animale con la proboscide', answer: 'ELEFANTE' },
  { clue: 'Edificio dove si studiano i libri', answer: 'SCUOLA' },
  { clue: 'Frutto arancione con la buccia dura', answer: 'ARANCIA' },
  { clue: 'Sport giocato in acqua con le pinne', answer: 'NUOTO' },
  { clue: 'Luogo dove si guardano i film', answer: 'CINEMA' },
  { clue: 'Antipasto italiano con fette di pane', answer: 'BRUSCHETTA' },
  { clue: 'Animale che muta la pelle', answer: 'SERPENTE' },
  { clue: 'Piatto italiano a forma di nastro', answer: 'TAGLIATELLE' },
  { clue: 'Mezzo di trasporto sui binari', answer: 'TRENO' },
  { clue: 'Grande corpo d\'acqua salata', answer: 'OCEANO' },
  { clue: 'Animale più veloce del mondo', answer: 'GHEPARDO' },
  { clue: 'Dolce tipico natalizio italiano', answer: 'PANETTONE' },
  { clue: 'Strumento a fiato con pistoni', answer: 'TROMBA' },
  { clue: 'Frutto tropicale con corona di foglie', answer: 'ANANAS' },
  { clue: 'Costruzione difensiva medievale', answer: 'CASTELLO' },
  { clue: 'Pianeta più grande del sistema solare', answer: 'GIOVE' },
  { clue: 'Metallo prezioso giallo', answer: 'ORO' },
  { clue: 'Stagione dei fiori', answer: 'PRIMAVERA' },
  { clue: 'Animale marsupiale australiano', answer: 'CANGURO' },
  { clue: 'Principale lingua parlata in Brasile', answer: 'PORTOGHESE' },
  { clue: 'Ingrediente base della pizza', answer: 'POMODORO' },
  { clue: 'Fenomeno atmosferico con fulmine', answer: 'TEMPORALE' },
  { clue: 'Numero che segue il nove', answer: 'DIECI' },
  { clue: 'Colore associato all\'invidia', answer: 'VERDE' },
  { clue: 'Città della Tour Eiffel', answer: 'PARIGI' },
  { clue: 'Animale domestico con baffi e artigli', answer: 'GATTO' },
  { clue: 'Sport olimpico con arco e frecce', answer: 'TIRO' },
  { clue: 'Punto cardinale opposto al Nord', answer: 'SUD' },
  { clue: 'Frutto viola allungato', answer: 'PRUGNA' },
  { clue: 'Periodo dell\'anno con 12 mesi', answer: 'ANNO' },
  { clue: 'Animale con il guscio', answer: 'TARTARUGA' },
  { clue: 'Principale fonte di energia solare', answer: 'SOLE' },
  { clue: 'Bevanda italiana effervescente', answer: 'SPUMANTE' },
  { clue: 'Struttura ossea del corpo umano', answer: 'SCHELETRO' },
  { clue: 'Gioco da tavolo con pedine nere e bianche', answer: 'SCACCHI' },
  { clue: 'Organo visivo del corpo umano', answer: 'OCCHIO' },
  { clue: 'Animale che vola di notte', answer: 'PIPISTRELLO' },
  { clue: 'Luogo dove si curano i malati', answer: 'OSPEDALE' },
  { clue: 'Pasta tipica siciliana', answer: 'ARANCINO' },
  { clue: 'Strumento a percussione con bacchette', answer: 'BATTERIA' },
  { clue: 'Monumento di Roma con l\'acqua', answer: 'FONTANA' },
  { clue: 'Insetto con ali colorate', answer: 'FARFALLA' },
  { clue: 'Colore del fuoco', answer: 'ROSSO' },
  { clue: 'Animale marino che cambia colore', answer: 'POLPO' },
  { clue: 'Dolce al cucchiaio con caffè', answer: 'TIRAMISU' },
  { clue: 'Sport invernale con gli sci', answer: 'SCI' },
  { clue: 'Piatto giapponese di riso con pesce', answer: 'SUSHI' },
  { clue: 'Fenomeno ottico nel cielo dopo la pioggia', answer: 'ARCOBALENO' },
  { clue: 'Contenitore per fiori', answer: 'VASO' },
  { clue: 'Frutto estivo rosso con semi neri', answer: 'ANGURIA' },
  { clue: 'Linguaggio informatico più famoso', answer: 'PYTHON' },
  { clue: 'Animale con il becco e piume', answer: 'UCCELLO' },
  { clue: 'Capitale dell\'Inghilterra', answer: 'LONDRA' },
  { clue: 'Pianta del deserto con spine', answer: 'CACTUS' },
  { clue: 'Sport con racchetta e volano', answer: 'BADMINTON' },
  { clue: 'Abitazione tipica degli eschimesi', answer: 'IGLOO' },
  { clue: 'Animale marino bianco e nero', answer: 'ORCA' },
  { clue: 'Strumento ottico per guardare lontano', answer: 'TELESCOPIO' },
  { clue: 'Pasta a forma di farfalla', answer: 'FARFALLE' },
  { clue: 'Montagna più alta del mondo', answer: 'EVEREST' },
  { clue: 'Sport con palla e canestro', answer: 'BASKET' },
  { clue: 'Dolce bianco tipico della Sicilia', answer: 'CANNOLO' },
  { clue: 'Edificio con molti uffici', answer: 'GRATTACIELO' },
  { clue: 'Animale con la criniera', answer: 'CAVALLO' },
  { clue: 'Stagione più calda', answer: 'ESTATE' },
  { clue: 'Frutto verde a forma di pera', answer: 'AVOCADO' },
  { clue: 'Animale che saltella e ha le orecchie lunghe', answer: 'CONIGLIO' },
  { clue: 'Luogo dove si comprano i libri', answer: 'LIBRERIA' },
  { clue: 'Sport americano con casco', answer: 'FOOTBALL' },
  { clue: 'Danza argentina passionale', answer: 'TANGO' },
  { clue: 'Frutto autunnale arancione', answer: 'CACHI' },
  { clue: 'Animale con sei zampe e antenne', answer: 'INSETTO' },
  { clue: 'Parte del corpo umano per pensare', answer: 'CERVELLO' },
  { clue: 'Arte di piegare la carta', answer: 'ORIGAMI' },
  { clue: 'Gara sportiva su lunga distanza', answer: 'MARATONA' },
  { clue: 'Recipiente di vetro per conservare', answer: 'BARATTOLO' },
  { clue: 'Animale con la proboscide e le zanne', answer: 'MAMMUT' },
  { clue: 'Canzone più conosciuta al mondo', answer: 'HAPPY' },
  { clue: 'Sport acquatico con la tavola', answer: 'SURF' },
  { clue: 'Colorante naturale rosso dei fiori', answer: 'ROSA' },
  { clue: 'Costruzione cinese famosa', answer: 'MURAGLIA' },
  { clue: 'Movimento dell\'aria', answer: 'VENTO' },
  { clue: 'Animale con la coda a sonagli', answer: 'COBRA' },
  { clue: 'Strumento di misura della temperatura', answer: 'TERMOMETRO' },
  { clue: 'Frutto con molti semi interni bianchi', answer: 'MELOGRANO' },
  { clue: 'Tipo di formaggio italiano duro', answer: 'PARMIGIANO' },
]

export function getShuffledQuestions(count = 30): CompletamentoQuestion[] {
  return [...QUESTIONS].sort(() => Math.random() - 0.5).slice(0, count)
}
