import { CompletamentoQuestion } from './types'

export const QUESTIONS: CompletamentoQuestion[] = [
  // --- ANIMALI ---
  { clue: 'Mammifero domestico da compagnia', answer: 'CANE' },
  { clue: 'Frutto tropicale ricco di potassio', answer: 'BANANA' },
  { clue: 'Pianeta roccioso dal colore rossastro', answer: 'MARTE' },
  { clue: 'Equino africano dalle strisce bianche e nere', answer: 'ZEBRA' },
  { clue: 'Grande felino con la criniera', answer: 'LEONE' },
  { clue: 'Mammifero terrestre con una lunga proboscide', answer: 'ELEFANTE' },
  { clue: 'Mollusco marino con tentacoli', answer: 'POLPO' },
  { clue: 'Marsupiale saltatore australiano', answer: 'CANGURO' },
  { clue: 'Felino africano tra i piu veloci', answer: 'GHEPARDO' },
  { clue: 'Rettile che cambia colore', answer: 'CAMALEONTE' },
  { clue: 'Uccello tropicale coloratissimo che parla', answer: 'PAPPAGALLO' },
  { clue: 'Animale con le pinne e un grande dente', answer: 'NARVALO' },
  { clue: 'Animale del bambù in Cina', answer: 'PANDA' },
  { clue: 'Insetto che produce miele', answer: 'APE' },
  { clue: 'Grande scimmia africana', answer: 'GORILLA' },
  { clue: 'Animale col guscio duro sulla schiena', answer: 'TARTARUGA' },
  { clue: 'Rettile più lungo del mondo', answer: 'ANACONDA' },
  { clue: 'Uccello polare che non vola', answer: 'PINGUINO' },
  { clue: 'Predatore del mare bianco e grigio', answer: 'SQUALO' },
  { clue: 'Mammifero marino con l\'eco', answer: 'DELFINO' },
  { clue: 'Il più grande carnivoro terrestre', answer: 'ORSO' },
  { clue: 'Animale notturno con le ali di membrana', answer: 'PIPISTRELLO' },
  { clue: 'Animale con le strisce sulla schiena che scava', answer: 'TASSO' },
  { clue: 'Uccello rapace notturno', answer: 'GUFO' },
  { clue: 'Animale con due gobbe nel deserto', answer: 'CAMMELLO' },
  { clue: 'Mammifero semi-acquatico con la coda piatta', answer: 'CASTORO' },
  { clue: 'Grande felino delle nevi dell\'Himalaya', answer: 'LEOPARDO' },
  { clue: 'Uccello più grande del mondo', answer: 'STRUZZO' },
  { clue: 'Animale marino con la stella', answer: 'STELLA' },
  { clue: 'Rettile con il collo lunghissimo', answer: 'GIRAFFA' },
  { clue: 'Mammifero che depone uova', answer: 'ORNITORINCO' },
  { clue: 'Uccello simbolo della pace', answer: 'COLOMBA' },
  { clue: 'Insetto con sei zampe e le antenne lunghe', answer: 'GRILLO' },
  { clue: 'Animale che passa da bruco a farfalla', answer: 'FARFALLA' },
  { clue: 'Grande felino con la criniera', answer: 'LEONE' },
  { clue: 'Piccolo mammifero con le spine', answer: 'RICCIO' },
  { clue: 'Animale marino che punge', answer: 'MEDUSA' },
  { clue: 'Piccolo roditore con la ruota in gabbia', answer: 'CRICETO' },
  { clue: 'Anfibio verde che salta', answer: 'RANA' },
  { clue: 'Animale bianco polare con pelliccia', answer: 'ERMELLINO' },

  // --- CALCIO ---
  { clue: 'Chi difende la porta nel calcio', answer: 'PORTIERE' },
  { clue: 'Tiro dal dischetto nel calcio', answer: 'RIGORE' },
  { clue: 'Colore del cartellino grave nel calcio', answer: 'ROSSO' },
  { clue: 'Il calcio all\'angolo del campo', answer: 'CORNER' },
  { clue: 'Chi dirige la partita', answer: 'ARBITRO' },
  { clue: 'Il trofeo del campionato italiano', answer: 'SCUDETTO' },
  { clue: 'Leggenda della Roma soprannominato "Il Capitano"', answer: 'TOTTI' },
  { clue: 'Il più grande calciatore argentino', answer: 'MESSI' },
  { clue: 'Portiere leggenda della Juventus', answer: 'BUFFON' },
  { clue: 'Calciatore soprannominato CR7', answer: 'RONALDO' },
  { clue: 'Il giovane fenomeno francese del PSG', answer: 'MBAPPE' },
  { clue: 'Il bomber norvegese del Manchester City', answer: 'HAALAND' },
  { clue: 'Competizione europea per club più importante', answer: 'CHAMPIONS' },
  { clue: 'Stadio della Juventus a Torino', answer: 'ALLIANZ' },
  { clue: 'Tecnica di superare l\'avversario col pallone', answer: 'DRIBBLING' },
  { clue: 'Passaggio che porta direttamente al gol', answer: 'ASSIST' },
  { clue: 'Campionato italiano di calcio', answer: 'SERIEA' },
  { clue: 'Il nome dello stadio di Milan e Inter', answer: 'SANSIRO' },
  { clue: 'Fuorigioco in inglese nel calcio', answer: 'OFFSIDE' },
  { clue: 'Gol segnato di testa', answer: 'COLPODTESTA' },
  { clue: 'Numero di giocatori in campo per squadra nel calcio', answer: 'UNDICI' },
  { clue: 'Il difensore che stoppa il bomber avversario', answer: 'TERZINO' },
  { clue: 'Il giocatore che gioca a metà campo', answer: 'CENTROCAMPISTA' },
  { clue: 'Soprannome del Bayern Monaco', answer: 'DIEROTEN' },
  { clue: 'Il presidente argentino del calcio mondiale', answer: 'INFANTINO' },
  { clue: 'Colore cartellino per diffida nel calcio', answer: 'GIALLO' },
  { clue: 'Il pallone usato al Mondiale 2022', answer: 'ALRIHLA' },
  { clue: 'La finale del campionato italiano coppa', answer: 'COPPA' },
  { clue: 'Ruolo dell\'attaccante centrale', answer: 'CENTRAVANTI' },
  { clue: 'Lo strumento del direttore di gara', answer: 'FISCHIETTO' },

  // --- SPORT ---
  { clue: 'Sport con racchetta e pallina gialla', answer: 'TENNIS' },
  { clue: 'Sport di velocità su quattro ruote con pit stop', answer: 'FORMULA' },
  { clue: 'Sport motociclistico su pista', answer: 'MOTOGP' },
  { clue: 'Sport olimpico di velocità in acqua', answer: 'NUOTO' },
  { clue: 'Gara podistica di 42 km', answer: 'MARATONA' },
  { clue: 'Sport con casco guantoni e ring', answer: 'BOXE' },
  { clue: 'Sport invernale sulle piste di neve', answer: 'SCI' },
  { clue: 'Sport con il canestro e la palla arancione', answer: 'BASKET' },
  { clue: 'Sport con rete alta e 6 giocatori per lato', answer: 'PALLAVOLO' },
  { clue: 'Sport inglese con uomini in maglia a righe', answer: 'RUGBY' },
  { clue: 'Atleta più veloce della storia', answer: 'BOLT' },
  { clue: 'Il numero uno del tennis mondiale per anni', answer: 'FEDERER' },
  { clue: 'Sport del birdie e del par', answer: 'GOLF' },
  { clue: 'Gara ciclistica più famosa d\'Italia', answer: 'GIRO' },
  { clue: 'Sport con spada e maschera', answer: 'SCHERMA' },
  { clue: 'Pilota di F1 con più titoli mondiali', answer: 'HAMILTON' },
  { clue: 'Campione italiano di MotoGP soprannominato "il Dottore"', answer: 'ROSSI' },
  { clue: 'Sport con frecce e bersaglio', answer: 'TIRO' },
  { clue: 'Sport acquatico con remi e canoa', answer: 'CANOA' },
  { clue: 'Sport su ghiaccio con pattini', answer: 'PATTINAGGIO' },
  { clue: 'Arte marziale giapponese in kimono bianco', answer: 'JUDO' },
  { clue: 'Sport olimpico con la ginnastica ritmica', answer: 'GINNASTICA' },
  { clue: 'Sport con il volante e la racchetta', answer: 'BADMINTON' },
  { clue: 'Gara ciclistica più famosa del mondo', answer: 'TOURDFRANCIA' },
  { clue: 'Sport su rotelle con mosse acrobatiche', answer: 'SKATEBOARD' },
  { clue: 'Sport con tiro al piattello', answer: 'TIRO' },
  { clue: 'Sport da tavolo con palline bianche piccole', answer: 'PINGPONG' },
  { clue: 'Sport d\'acqua che si fa con la tavola e le onde', answer: 'SURF' },

  // --- MUSICA ---
  { clue: 'Strumento a corde pizzicate con 6 corde', answer: 'CHITARRA' },
  { clue: 'Strumento a 88 tasti bianchi e neri', answer: 'PIANOFORTE' },
  { clue: 'Frontman dei Queen', answer: 'MERCURY' },
  { clue: 'Gruppo musicale di Liverpool degli anni 60', answer: 'BEATLES' },
  { clue: 'Re del pop americano morto nel 2009', answer: 'JACKSON' },
  { clue: 'Festival musicale più importante d\'Italia', answer: 'SANREMO' },
  { clue: 'Cantante italiano soprannominato il Blasco', answer: 'VASCO' },
  { clue: 'Strumento a fiato del jazz per eccellenza', answer: 'SASSOFONO' },
  { clue: 'Strumento a percussione della batteria', answer: 'RULLANTE' },
  { clue: 'Cantante di "Shape of You"', answer: 'SHEERAN' },
  { clue: 'La cantante di "Poker Face"', answer: 'GAGA' },
  { clue: 'Genere musicale nato nei ghetti americani', answer: 'RAP' },
  { clue: 'Il re del rock americano degli anni 50', answer: 'ELVIS' },
  { clue: 'La voce degli U2', answer: 'BONO' },
  { clue: 'Strumento musicale a corde dell\'orchestra', answer: 'VIOLINO' },
  { clue: 'Genere musicale brasiliano con maracas', answer: 'SAMBA' },
  { clue: 'Cantante di "Bohemian Rhapsody"', answer: 'FREDDIE' },
  { clue: 'Il gruppo rock di Mick Jagger', answer: 'ROLLINGSTONES' },
  { clue: 'Strumento tipico della musica irlandese', answer: 'ARPA' },
  { clue: 'Cantante pop svedese degli anni 70 con ABBA', answer: 'ABBA' },
  { clue: 'Il cantante di Thriller', answer: 'MICHAEL' },
  { clue: 'Strumento a fiato lungo d\'orchestra', answer: 'FLAUTO' },
  { clue: 'Cantante italiana vincitrice di Sanremo 2022', answer: 'MAHMOOD' },
  { clue: 'La cantante di "Chandelier"', answer: 'SIA' },
  { clue: 'Tipo di musica elettronica per ballare', answer: 'TECHNO' },
  { clue: 'Strumento usato nel flamenco spagnolo', answer: 'NACCHERE' },
  { clue: 'Il cantante di "Yesterday"', answer: 'MCCARTNEY' },
  { clue: 'Cantante italiana di "Grande"', answer: 'TIZIANO' },
  { clue: 'La band di "Smells Like Teen Spirit"', answer: 'NIRVANA' },
  { clue: 'Strumento con doppia ancia del jazz', answer: 'CLARINETTO' },

  // --- GEOGRAFIA ---
  { clue: 'La città con la Torre Eiffel', answer: 'PARIGI' },
  { clue: 'Capitale del Giappone', answer: 'TOKYO' },
  { clue: 'Il fiume più lungo del mondo', answer: 'NILO' },
  { clue: 'Il deserto più grande del mondo', answer: 'SAHARA' },
  { clue: 'La montagna più alta del mondo', answer: 'EVEREST' },
  { clue: 'Isola vulcanica a sud dell\'Italia', answer: 'SICILIA' },
  { clue: 'Il paese più piccolo del mondo', answer: 'VATICANO' },
  { clue: 'Il continente più freddo del mondo', answer: 'ANTARTIDE' },
  { clue: 'Capitale dell\'Australia', answer: 'CANBERRA' },
  { clue: 'Il vulcano attivo siciliano', answer: 'ETNA' },
  { clue: 'Il lago più grande del mondo', answer: 'CASPIO' },
  { clue: 'La capitale del Brasile', answer: 'BRASILIA' },
  { clue: 'Il paese delle mille isole nel sud-est asiatico', answer: 'INDONESIA' },
  { clue: 'La capitale della Germania', answer: 'BERLINO' },
  { clue: 'Il paese più grande del mondo', answer: 'RUSSIA' },
  { clue: 'Catena montuosa tra Italia e Francia', answer: 'ALPI' },
  { clue: 'Il mare che separa Italia dalla Grecia', answer: 'ADRIATICO' },
  { clue: 'La foresta pluviale più grande del mondo', answer: 'AMAZZONIA' },
  { clue: 'Il paese con più isole del mondo', answer: 'SVEZIA' },
  { clue: 'Capitale della Russia', answer: 'MOSCA' },
  { clue: 'Il fiume sacro dell\'India', answer: 'GANGE' },
  { clue: 'La cascata delle cascate del Niagara si trova tra USA e questo paese', answer: 'CANADA' },
  { clue: 'Il continente più grande', answer: 'ASIA' },
  { clue: 'Capitale della Spagna', answer: 'MADRID' },
  { clue: 'Il paese dove si trova la Grande Muraglia', answer: 'CINA' },
  { clue: 'Capitale del Portogallo', answer: 'LISBONA' },
  { clue: 'Il mar che si trova a est dell\'Italia', answer: 'ADRIATICO' },
  { clue: 'Il paese scandinavo con i fiordi', answer: 'NORVEGIA' },
  { clue: 'La penisola dove si trova l\'Italia', answer: 'APPENNINICA' },
  { clue: 'Capitale dell\'Argentina', answer: 'BUENOSAIRES' },

  // --- STORIA ---
  { clue: 'Il famoso combattente romano dell\'arena', answer: 'GLADIATORE' },
  { clue: 'Imperatore di Francia poi esiliato a Sant\'Elena', answer: 'NAPOLEONE' },
  { clue: 'Conquistatore dell\'America nel 1492', answer: 'COLOMBO' },
  { clue: 'Il re egizio figlio di Dio del sole', answer: 'FARAONE' },
  { clue: 'L\'anfiteatro romano di Roma', answer: 'COLOSSEO' },
  { clue: 'Monumento funebre egizio a forma di triangolo', answer: 'PIRAMIDE' },
  { clue: 'Guerriero medievale a cavallo con armatura', answer: 'CAVALIERE' },
  { clue: 'Il leader comunista sovietico della WWII', answer: 'STALIN' },
  { clue: 'Il genio di Vinci pittore e inventore', answer: 'LEONARDO' },
  { clue: 'Il filosofo greco maestro di Alessandro Magno', answer: 'ARISTOTELE' },
  { clue: 'La rivoluzione del 1789 in Francia', answer: 'RIVOLUZIONE' },
  { clue: 'Il muro abbattuto nel 1989 a Berlino', answer: 'MURO' },
  { clue: 'Navigatore portoghese che circumnavigò il globo', answer: 'MAGELLANO' },
  { clue: 'Il primo uomo sulla Luna nel 1969', answer: 'ARMSTRONG' },
  { clue: 'Il condottiero greco che conquistò la Persia', answer: 'ALESSANDRO' },
  { clue: 'Il re degli Unni che terrorizzò l\'Europa', answer: 'ATTILA' },
  { clue: 'Il primo imperatore di Roma', answer: 'AUGUSTO' },
  { clue: 'Il filosofo greco che bevve la cicuta', answer: 'SOCRATE' },
  { clue: 'Il leader della Rivoluzione russa', answer: 'LENIN' },
  { clue: 'L\'ultimo faraone d\'Egitto', answer: 'CLEOPATRA' },
  { clue: 'Il papa che ordinò le crociate', answer: 'URBANO' },
  { clue: 'Il re dei Franchi coronato imperatore', answer: 'CARLOMAGNO' },
  { clue: 'Il presidente americano che abolì la schiavitù', answer: 'LINCOLN' },
  { clue: 'Il marinaio genovese che scoprì il Nuovo Mondo', answer: 'COLOMBO' },
  { clue: 'Il guerriero di Sparta difensore delle Termopili', answer: 'LEONIDA' },
  { clue: 'Il generale cartaginese che attraversò le Alpi', answer: 'ANNIBALE' },
  { clue: 'Il pittore e inventore che dipinse la Gioconda', answer: 'DAVINCI' },
  { clue: 'Il poeta romano che scrisse l\'Eneide', answer: 'VIRGILIO' },

  // --- MACCHINE E MOTO ---
  { clue: 'Marca italiana di supercar con il cavallino rampante', answer: 'FERRARI' },
  { clue: 'Marca italiana di supercar con il toro', answer: 'LAMBORGHINI' },
  { clue: 'Marca tedesca di auto con le quattro ruote incrociate', answer: 'AUDI' },
  { clue: 'Marca americana di moto famose per il suono', answer: 'HARLEY' },
  { clue: 'Marca italiana di moto sportive', answer: 'DUCATI' },
  { clue: 'Auto elettrica del visionario Elon Musk', answer: 'TESLA' },
  { clue: 'Il campione di F1 che ha vinto 7 titoli', answer: 'SCHUMACHER' },
  { clue: 'Il pneumatico della moto o dell\'auto', answer: 'GOMMA' },
  { clue: 'La sosta in F1 per cambiare le gomme', answer: 'PITSTOP' },
  { clue: 'Marca giapponese di moto con la N', answer: 'NINJA' },
  { clue: 'La gara automobilistica più famosa del mondo a Monaco', answer: 'MONTECARLO' },
  { clue: 'Il campione olandese attuale di F1', answer: 'VERSTAPPEN' },
  { clue: 'La casa automobilistica di Maranello', answer: 'FERRARI' },
  { clue: 'Il brand auto con il logo a tre punte', answer: 'MERCEDES' },
  { clue: 'La moto sportiva di Aprilia', answer: 'RSV' },
  { clue: 'Il circuito italiano di F1 nel parco di Monza', answer: 'MONZA' },
  { clue: 'Il cognome del pilota italiano Valentino', answer: 'ROSSI' },
  { clue: 'Il marchio auto di Wolfsburg in Germania', answer: 'VOLKSWAGEN' },
  { clue: 'Il modello sportivo della Porsche a coda di balena', answer: 'PORSCHE' },
  { clue: 'Il tipo di motore con due cilindri opposti', answer: 'BOXER' },
  { clue: 'Brand auto premium con il leone di Baviera', answer: 'BMW' },
  { clue: 'Il campione di MotoGP con record di vittorie Marc', answer: 'MARQUEZ' },
  { clue: 'L\'azienda giapponese che fa la Kawasaki Ninja', answer: 'KAWASAKI' },
  { clue: 'La casa auto italiana di economia FIAT', answer: 'FIAT' },
  { clue: 'Lo schermo informativo sul cruscotto digitale', answer: 'DISPLAY' },

  // --- CIBO E CUCINA ---
  { clue: 'Pasta al sugo con uova e guanciale', answer: 'CARBONARA' },
  { clue: 'Dolce italiano al caffè con mascarpone', answer: 'TIRAMISU' },
  { clue: 'Primo piatto italiano a base di riso', answer: 'RISOTTO' },
  { clue: 'Dolce siciliano fritto con ricotta', answer: 'CANNOLO' },
  { clue: 'Piatto giapponese di riso e pesce crudo', answer: 'SUSHI' },
  { clue: 'Crema gelata italiana', answer: 'GELATO' },
  { clue: 'Formaggio duro padano grattugiato', answer: 'PARMIGIANO' },
  { clue: 'Salume rosa di Bologna', answer: 'MORTADELLA' },
  { clue: 'Bevanda alcolica italiana con Aperol', answer: 'SPRITZ' },
  { clue: 'Formaggio morbido bianco di bufala', answer: 'MOZZARELLA' },
  { clue: 'Pasta lunga più celebre al mondo', answer: 'SPAGHETTI' },
  { clue: 'Piatto messicano con tortilla', answer: 'TACOS' },
  { clue: 'Croissant in italiano', answer: 'CORNETTO' },
  { clue: 'La pasta al forno con besciamella', answer: 'LASAGNA' },
  { clue: 'Il pane toscano insipido', answer: 'TOSCANO' },
  { clue: 'Il vino bianco frizzante veneto', answer: 'PROSECCO' },
  { clue: 'Il caffè ristretto molto denso', answer: 'ESPRESSO' },
  { clue: 'La zuppa di pesce livornese', answer: 'CACCIUCCO' },
  { clue: 'Il salume tipico di Parma', answer: 'PROSCIUTTO' },
  { clue: 'La pasta corta con buco nel mezzo', answer: 'RIGATONI' },
  { clue: 'Il dolce napoletano con sfoglia e crema', answer: 'SFOGLIATELLA' },
  { clue: 'Il fungo pregiato usato sulle tagliatelle', answer: 'TARTUFO' },
  { clue: 'La bevanda calda con latte e caffè', answer: 'CAPPUCCINO' },
  { clue: 'Il formaggio svizzero con i buchi', answer: 'EMMENTAL' },
  { clue: 'La pasta con ragù di carne bolognese', answer: 'TAGLIATELLE' },
  { clue: 'Il sugo base della pasta all\'arrabbiata', answer: 'POMODORO' },
  { clue: 'L\'olio prodotto dalle olive', answer: 'OLIO' },
  { clue: 'Il vino rosso toscano famoso nel mondo', answer: 'CHIANTI' },
  { clue: 'La frittata di patate spagnola', answer: 'TORTILLA' },
  { clue: 'Il dolce americano con cioccolato e noci', answer: 'BROWNIE' },

  // --- CULTURA GENERALE E DIVERTIMENTO ---
  { clue: 'Il social network delle foto fondato da Zuckerberg', answer: 'FACEBOOK' },
  { clue: 'La piattaforma di video più grande del mondo', answer: 'YOUTUBE' },
  { clue: 'Il film più costoso della storia con l\'iceberg', answer: 'TITANIC' },
  { clue: 'Il personaggio Marvel con lo scudo', answer: 'CAPITAN' },
  { clue: 'Il mago di Hogwarts con la cicatrice', answer: 'POTTER' },
  { clue: 'Il gioco da tavolo dove si comprano casette', answer: 'MONOPOLY' },
  { clue: 'Il gioco di carte italiano a 40 carte', answer: 'BRISCOLA' },
  { clue: 'La bevanda calda del mattino degli italiani', answer: 'CAFFE' },
  { clue: 'Il personaggio Disney con le orecchie tonde', answer: 'TOPOLINO' },
  { clue: 'Il film di James Cameron con i Na\'vi', answer: 'AVATAR' },
  { clue: 'La serie TV dei draghi e del Trono', answer: 'GAME' },
  { clue: 'L\'attore di Iron Man', answer: 'DOWNEY' },
  { clue: 'Il gioco dei mattoncini colorati danese', answer: 'LEGO' },
  { clue: 'Il social delle storie che spariscono', answer: 'SNAPCHAT' },
  { clue: 'Il personaggio dei cartoni con gli occhi a mandorla giapponesi', answer: 'ANIME' },
  { clue: 'Il gioco in cui si costruisce su un\'isola deserta', answer: 'MINECRAFT' },
  { clue: 'Il franchise cinematografico con i supereroi Marvel', answer: 'AVENGERS' },
  { clue: 'Il cantante di "Thriller"', answer: 'JACKSON' },
  { clue: 'Il personaggio della Disney con i capelli rossi che vive nel mare', answer: 'SIRENETTA' },
  { clue: 'La piattaforma di video brevi cinese', answer: 'TIKTOK' },
  { clue: 'Il robot buono della saga di Star Wars', answer: 'ARTOO' },
  { clue: 'Il film di Pixar con i giocattoli che vivono', answer: 'TOYSTORY' },
  { clue: 'Il personaggio con il naso che cresce quando mente', answer: 'PINOCCHIO' },
  { clue: 'La serie animata giapponese con i mostriciattoli tascabili', answer: 'POKEMON' },
  { clue: 'Il gioco online con 100 giocatori sull\'isola', answer: 'FORTNITE' },
  { clue: 'Il personaggio della Marvel con il tridente del mare', answer: 'NAMOR' },
  { clue: 'La consolle portatile di Nintendo', answer: 'SWITCH' },
  { clue: 'L\'app per la messaggistica istantanea più usata in Italia', answer: 'WHATSAPP' },

  // --- SCIENZA E TECNOLOGIA ---
  { clue: 'La formula dell\'acqua', answer: 'HDUE O' },
  { clue: 'Il simbolo chimico dell\'oro', answer: 'AU' },
  { clue: 'Il pianeta più vicino alla Terra', answer: 'MARTE' },
  { clue: 'Lo strumento per misurare la temperatura', answer: 'TERMOMETRO' },
  { clue: 'Il numero di pianeti del sistema solare', answer: 'OTTO' },
  { clue: 'La macchina per calcolare inventata da Turing', answer: 'COMPUTER' },
  { clue: 'Lo scienziato che scoprì la gravitazione', answer: 'NEWTON' },
  { clue: 'Il fisico della relatività', answer: 'EINSTEIN' },
  { clue: 'Il satellite naturale della Terra', answer: 'LUNA' },
  { clue: 'La stella al centro del sistema solare', answer: 'SOLE' },
  { clue: 'Il gas più abbondante nell\'aria', answer: 'AZOTO' },
  { clue: 'Il metallo più leggero della tavola periodica', answer: 'LITIO' },
  { clue: 'Lo strumento ottico per guardare le stelle', answer: 'TELESCOPIO' },
  { clue: 'L\'energia rinnovabile del vento', answer: 'EOLICA' },
  { clue: 'La particella subatomica carica negativamente', answer: 'ELETTRONE' },
  { clue: 'Il tipo di energia prodotta dal sole', answer: 'SOLARE' },
  { clue: 'La molecola portante del codice genetico', answer: 'DNA' },
  { clue: 'Il pianeta con gli anelli più spettacolari', answer: 'SATURNO' },
  { clue: 'Lo strumento per sentire il battito cardiaco', answer: 'STETOSCOPIO' },
  { clue: 'Il tipo di roccia formatosi da magma raffreddato', answer: 'IGNEA' },

  // --- ARTE E LETTERATURA ---
  { clue: 'Il libro sacro dei cristiani', answer: 'BIBBIA' },
  { clue: 'Il pittore che dipinse gli "Iris"', answer: 'VANGOGH' },
  { clue: 'Il libro di Dante che descrive l\'inferno', answer: 'COMMEDIA' },
  { clue: 'Il personaggio di Cervantes con la lancia', answer: 'DONCHISCIOTTE' },
  { clue: 'La scultura più famosa di Michelangelo', answer: 'DAVID' },
  { clue: 'Il poeta romano dell\'Eneide', answer: 'VIRGILIO' },
  { clue: 'Il romanzo di Hemingway sulla guerra', answer: 'ADDIO' },
  { clue: 'Il pittore del Guernica', answer: 'PICASSO' },
  { clue: 'Il romanzo distopico di Orwell con il Grande Fratello', answer: 'MILLENOVEOTTANTAQUATTRO' },
  { clue: 'Il personaggio di Conan Doyle con la pipa', answer: 'HOLMES' },
  { clue: 'La commedia italiana scritta da Goldoni', answer: 'ARLECCHINO' },
  { clue: 'Il museo parigino più visitato al mondo', answer: 'LOUVRE' },
  { clue: 'Il movimento artistico di Picasso e Braque', answer: 'CUBISMO' },
  { clue: 'La scrittrice di Orgoglio e Pregiudizio', answer: 'AUSTEN' },
  { clue: 'Il poeta romano dell\'Iliade', answer: 'OMERO' },
  { clue: 'Il teatro più famoso di Venezia', answer: 'FENICE' },
  { clue: 'Il pittore fiammingo degli specchi nelle stanze', answer: 'VERMEER' },
  { clue: 'L\'autore del Faust', answer: 'GOETHE' },
  { clue: 'Il personaggio di Tolstoy che guarda la guerra da fuori', answer: 'GUERRA' },
  { clue: 'La città museo d\'arte più famosa d\'Italia', answer: 'FIRENZE' },

  // --- PAESI E CAPITALI ---
  { clue: 'Capitale del Messico', answer: 'MEXICO' },
  { clue: 'Capitale della Cina', answer: 'PECHINO' },
  { clue: 'Capitale del Canada', answer: 'OTTAWA' },
  { clue: 'Capitale dell\'India', answer: 'NUOVADHELI' },
  { clue: 'Capitale del Sudafrica', answer: 'PRETORIA' },
  { clue: 'Capitale dell\'Egitto', answer: 'ILCAIRO' },
  { clue: 'Capitale della Turchia', answer: 'ANKARA' },
  { clue: 'Capitale della Grecia', answer: 'ATENE' },
  { clue: 'Capitale della Svezia', answer: 'STOCCOLMA' },
  { clue: 'Capitale dell\'Austria', answer: 'VIENNA' },
  { clue: 'Capitale dei Paesi Bassi', answer: 'AMSTERDAM' },
  { clue: 'Capitale dell\'Irlanda', answer: 'DUBLINO' },
  { clue: 'Capitale della Polonia', answer: 'VARSAVIA' },
  { clue: 'Capitale della Romania', answer: 'BUCAREST' },
  { clue: 'Capitale del Belgio', answer: 'BRUXELLES' },
  { clue: 'Capitale della Svizzera', answer: 'BERNA' },
  { clue: 'Capitale della Norvegia', answer: 'OSLO' },
  { clue: 'Capitale della Danimarca', answer: 'COPENAGHEN' },
  { clue: 'Capitale del Perù', answer: 'LIMA' },
  { clue: 'Capitale del Kenya', answer: 'NAIROBI' },

  // --- CORPO UMANO E SALUTE ---
  { clue: 'Il muscolo cardiaco che pompa il sangue', answer: 'CUORE' },
  { clue: 'L\'organo che filtra le tossine nel sangue', answer: 'FEGATO' },
  { clue: 'L\'osso più lungo del corpo umano', answer: 'FEMORE' },
  { clue: 'L\'organo che permette la respirazione', answer: 'POLMONE' },
  { clue: 'Il sistema nervoso centrale più importante', answer: 'CERVELLO' },
  { clue: 'Il liquido rosso che scorre nelle vene', answer: 'SANGUE' },
  { clue: 'Il dente più acuminato in bocca', answer: 'CANINO' },
  { clue: 'L\'organo che raccoglie le urine', answer: 'VESCICA' },
  { clue: 'Il numero di vertebre cervicali', answer: 'SETTE' },
  { clue: 'Il tipo di sangue più comune', answer: 'AZERO' },
  { clue: 'La parte esterna protettiva del corpo', answer: 'PELLE' },
  { clue: 'Il liquido prodotto dalle ghiandole lacrimali', answer: 'LACRIME' },
  { clue: 'Il tendine sotto il ginocchio', answer: 'ROTULEO' },
  { clue: 'Il numero di denti definitivi dell\'adulto', answer: 'TRENTADUE' },
  { clue: 'Il muscolo addominale più superficiale', answer: 'RETTO' },

  // --- MATEMATICA ---
  { clue: 'Il numero primo dopo il 7', answer: 'UNDICI' },
  { clue: 'La radice quadrata di 100', answer: 'DIECI' },
  { clue: 'Il risultato di 9 per 9', answer: 'OTTANTUNO' },
  { clue: 'Il numero di lati di un ottagono', answer: 'OTTO' },
  { clue: 'Il primo numero naturale', answer: 'ZERO' },
  { clue: 'Il risultato di 7 per 7', answer: 'QUARANTANOVE' },
  { clue: 'La costante matematica per le circonferenze', answer: 'PIGRECO' },
  { clue: 'La somma degli angoli interni di un quadrilatero', answer: 'TRECENTOSESSANTA' },
  { clue: 'Il risultato di 12 per 12', answer: 'CENTOQUARANTAQUATTRO' },
  { clue: 'Il tipo di triangolo con tutti lati uguali', answer: 'EQUILATERO' },
  { clue: 'Il numero che moltiplicato per qualsiasi numero dà zero', answer: 'ZERO' },
  { clue: 'Il risultato di 100 meno 37', answer: 'SESSANTATRE' },
  { clue: 'Il valore numerico della metà di 80', answer: 'QUARANTA' },
  { clue: 'Il tipo di angolo maggiore di 90 gradi', answer: 'OTTUSO' },
  { clue: 'La somma di tutti i numeri da 1 a 10', answer: 'CINQUANTACINQUE' },

  // --- NATURA E PIANTE ---
  { clue: 'Il fiore simbolo dell\'amore', answer: 'ROSA' },
  { clue: 'L\'albero dei frutti delle ghiande', answer: 'QUERCIA' },
  { clue: 'Il fungo velenoso rosso con i puntini bianchi', answer: 'AMANITA' },
  { clue: 'La pianta grassa del deserto con spine', answer: 'CACTUS' },
  { clue: 'Il fiore giallo del sole', answer: 'GIRASOLE' },
  { clue: 'L\'albero natalizio sempreverde', answer: 'ABETE' },
  { clue: 'Il fiore viola tipico dei campi della Provenza', answer: 'LAVANDA' },
  { clue: 'La pianta acquatica con il fiore bianco', answer: 'NINFEA' },
  { clue: 'Il fungo pregiato che si trova sotto terra', answer: 'TARTUFO' },
  { clue: 'L\'albero dei limoni e delle arance', answer: 'AGRUME' },
  { clue: 'La pianta rampicante dei vigneti', answer: 'VITE' },
  { clue: 'Il grano che cresce nelle risaie', answer: 'RISO' },
  { clue: 'L\'albero dei fichi', answer: 'FICO' },
  { clue: 'Il fiore primaverile a campanello bianco', answer: 'MUGHETTO' },
  { clue: 'La fronda sempreverde usata a Natale', answer: 'VISCHIO' },

  // --- PROFESSIONI ---
  { clue: 'Chi cura i denti', answer: 'DENTISTA' },
  { clue: 'Chi cuce abiti', answer: 'SARTO' },
  { clue: 'Chi vola gli aerei', answer: 'PILOTA' },
  { clue: 'Chi costruisce le case', answer: 'MURATORE' },
  { clue: 'Chi insegna a scuola', answer: 'INSEGNANTE' },
  { clue: 'Chi disegna gli edifici', answer: 'ARCHITETTO' },
  { clue: 'Chi cura gli animali', answer: 'VETERINARIO' },
  { clue: 'Chi difende in tribunale', answer: 'AVVOCATO' },
  { clue: 'Chi studia le stelle', answer: 'ASTRONOMO' },
  { clue: 'Chi cucina in un ristorante', answer: 'CUOCO' },
  { clue: 'Chi scatta le fotografie', answer: 'FOTOGRAFO' },
  { clue: 'Chi ripara le macchine', answer: 'MECCANICO' },
  { clue: 'Chi taglia i capelli', answer: 'PARRUCCHIERE' },
  { clue: 'Chi spegne gli incendi', answer: 'POMPIERE' },
  { clue: 'Chi traduce le lingue', answer: 'TRADUTTORE' },

  // --- OGGETTI DI CASA ---
  { clue: 'L\'elettrodomestico che raffredda i cibi', answer: 'FRIGORIFERO' },
  { clue: 'Lo strumento per guardare la TV', answer: 'TELECOMANDO' },
  { clue: 'Il mobile dove si dormono i sogni', answer: 'LETTO' },
  { clue: 'L\'elettrodomestico che lava i piatti', answer: 'LAVASTOVIGLIE' },
  { clue: 'Lo strumento per scaldare velocemente il cibo', answer: 'MICROONDE' },
  { clue: 'Il mobile dove si ripongono i vestiti', answer: 'ARMADIO' },
  { clue: 'L\'utensile per tagliare il cibo', answer: 'COLTELLO' },
  { clue: 'Il contenitore per cuocere la pasta', answer: 'PENTOLA' },
  { clue: 'Lo strumento per stirare i vestiti', answer: 'FERRO' },
  { clue: 'L\'elettrodomestico che aspira la polvere', answer: 'ASPIRAPOLVERE' },
  { clue: 'Il sanitario bianco del bagno', answer: 'VASCA' },
  { clue: 'Il mobile basso su cui si appoggia la TV', answer: 'MOBILETTO' },
  { clue: 'La lampada sul comodino', answer: 'ABAJOUR' },
  { clue: 'Il tavolo dove si mangia', answer: 'TAVOLA' },
  { clue: 'Lo strumento per bollire l\'acqua velocemente', answer: 'BOLLITORE' },
]

export function getShuffledQuestions(count = 30): CompletamentoQuestion[] {
  return [...QUESTIONS].sort(() => Math.random() - 0.5).slice(0, count)
}
