import { Question } from './types'

export const QUESTIONS: Question[] = [
  // --- CULTURA GENERALE ---
  { question: 'Qual è la capitale d\'Italia?', optionA: 'Roma', optionB: 'Milano', correctAnswer: 'A' },
  { question: 'Quanti colori ha la bandiera italiana?', optionA: 'Tre', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'In quale anno è finita la Seconda Guerra Mondiale?', optionA: '1945', optionB: '1939', correctAnswer: 'A' },
  { question: 'Chi ha dipinto la Cappella Sistina?', optionA: 'Michelangelo', optionB: 'Leonardo', correctAnswer: 'A' },
  { question: 'Quanti pianeti ha il Sistema Solare?', optionA: 'Otto', optionB: 'Nove', correctAnswer: 'A' },
  { question: 'Quale pianeta è più vicino al Sole?', optionA: 'Mercurio', optionB: 'Venere', correctAnswer: 'A' },
  { question: 'Chi ha scritto la Divina Commedia?', optionA: 'Dante Alighieri', optionB: 'Petrarca', correctAnswer: 'A' },
  { question: 'Qual è la montagna più alta del mondo?', optionA: 'Everest', optionB: 'K2', correctAnswer: 'A' },
  { question: 'In quale oceano si trova l\'Australia?', optionA: 'Pacifico', optionB: 'Indiano', correctAnswer: 'A' },
  { question: 'Quante sono le meraviglie del mondo antico?', optionA: 'Sette', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Qual è l\'elemento chimico con simbolo O?', optionA: 'Ossigeno', optionB: 'Oro', correctAnswer: 'A' },
  { question: 'Chi ha inventato il telefono?', optionA: 'Alexander Graham Bell', optionB: 'Thomas Edison', correctAnswer: 'A' },
  { question: 'Quante corde ha una chitarra classica?', optionA: 'Sei', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Quale paese ha la popolazione più alta al mondo?', optionA: 'India', optionB: 'Cina', correctAnswer: 'A' },
  { question: 'Qual è la capitale della Francia?', optionA: 'Parigi', optionB: 'Marsiglia', correctAnswer: 'A' },
  { question: 'Quante lettere ha l\'alfabeto italiano?', optionA: '21', optionB: '26', correctAnswer: 'A' },
  { question: 'Quale organo produce l\'insulina?', optionA: 'Pancreas', optionB: 'Fegato', correctAnswer: 'A' },
  { question: 'In quale città si trova il Colosseo?', optionA: 'Roma', optionB: 'Napoli', correctAnswer: 'A' },
  { question: 'Quanti continenti ci sono sulla Terra?', optionA: 'Sette', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'Qual è il paese più grande del mondo per superficie?', optionA: 'Russia', optionB: 'Canada', correctAnswer: 'A' },
  { question: 'Qual è il simbolo chimico dell\'oro?', optionA: 'Au', optionB: 'Ag', correctAnswer: 'A' },
  { question: 'Quante ore ha un giorno?', optionA: '24', optionB: '20', correctAnswer: 'A' },
  { question: 'In quale paese si trova la Torre di Pisa?', optionA: 'Italia', optionB: 'Spagna', correctAnswer: 'A' },
  { question: 'Quale pianeta è il più grande del Sistema Solare?', optionA: 'Giove', optionB: 'Saturno', correctAnswer: 'A' },
  { question: 'Quante settimane ha un anno?', optionA: '52', optionB: '48', correctAnswer: 'A' },
  { question: 'Qual è la velocità della luce in km/s approssimata?', optionA: '300.000 km/s', optionB: '150.000 km/s', correctAnswer: 'A' },
  { question: 'Chi ha fondato Apple?', optionA: 'Steve Jobs', optionB: 'Bill Gates', correctAnswer: 'A' },
  { question: 'Quante ossa ha il corpo umano adulto?', optionA: '206', optionB: '180', correctAnswer: 'A' },
  { question: 'Qual è la capitale della Germania?', optionA: 'Berlino', optionB: 'Monaco', correctAnswer: 'A' },
  { question: 'Chi ha scritto Romeo e Giulietta?', optionA: 'Shakespeare', optionB: 'Dickens', correctAnswer: 'A' },
  { question: 'In quale anno è stato inventato internet?', optionA: '1969', optionB: '1989', correctAnswer: 'A' },
  { question: 'Quale è il colore primario che manca: rosso, giallo, ...?', optionA: 'Blu', optionB: 'Verde', correctAnswer: 'A' },
  { question: 'Qual è l\'animale più alto del mondo?', optionA: 'Giraffa', optionB: 'Elefante', correctAnswer: 'A' },
  { question: 'In quale città si trova la Sagrada Familia?', optionA: 'Barcellona', optionB: 'Madrid', correctAnswer: 'A' },
  { question: 'Quanti mesi ha un anno?', optionA: 'Dodici', optionB: 'Tredici', correctAnswer: 'A' },
  { question: 'Quale è il continente più grande?', optionA: 'Asia', optionB: 'Africa', correctAnswer: 'A' },
  { question: 'Chi ha dipinto l\'Ultima Cena?', optionA: 'Leonardo da Vinci', optionB: 'Raffaello', correctAnswer: 'A' },
  { question: 'Quanti grammi ha un chilogrammo?', optionA: '1000', optionB: '100', correctAnswer: 'A' },
  { question: 'Qual è la formula dell\'acqua?', optionA: 'H2O', optionB: 'H2O2', correctAnswer: 'A' },
  { question: 'Chi ha scritto il Pinocchio?', optionA: 'Carlo Collodi', optionB: 'Edmondo De Amicis', correctAnswer: 'A' },

  // --- CALCIO ITALIANO ---
  { question: 'Quale squadra ha vinto più scudetti nella storia?', optionA: 'Juventus', optionB: 'Inter', correctAnswer: 'A' },
  { question: 'In quale città gioca la Juventus?', optionA: 'Torino', optionB: 'Milano', correctAnswer: 'A' },
  { question: 'Come si chiama lo stadio del Milan?', optionA: 'San Siro', optionB: 'Olimpico', correctAnswer: 'A' },
  { question: 'Quale squadra ha la maglia a strisce verticali bianconere?', optionA: 'Juventus', optionB: 'Inter', correctAnswer: 'A' },
  { question: 'Quante volte ha vinto l\'Italia il Mondiale di calcio?', optionA: 'Quattro', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'In quale anno l\'Italia ha vinto l\'ultimo Europeo?', optionA: '2021', optionB: '2012', correctAnswer: 'A' },
  { question: 'Come si chiama il giocatore soprannominato "Il Capitano" alla Roma?', optionA: 'Francesco Totti', optionB: 'Daniele De Rossi', correctAnswer: 'A' },
  { question: 'In quale città gioca il Napoli?', optionA: 'Napoli', optionB: 'Bari', correctAnswer: 'A' },
  { question: 'Quale colore è la maglia dell\'Inter?', optionA: 'Nerazzurra', optionB: 'Bianconera', correctAnswer: 'A' },
  { question: 'Chi allenava l\'Italia quando vinse il Mondiale 2006?', optionA: 'Marcello Lippi', optionB: 'Giovanni Trapattoni', correctAnswer: 'A' },
  { question: 'Quale squadra gioca allo stadio Diego Armando Maradona?', optionA: 'Napoli', optionB: 'Palermo', correctAnswer: 'A' },
  { question: 'Quante squadre partecipano alla Serie A?', optionA: 'Venti', optionB: 'Diciotto', correctAnswer: 'A' },
  { question: 'Chi è il capocannoniere di tutti i tempi della Serie A?', optionA: 'Silvio Piola', optionB: 'Francesco Totti', correctAnswer: 'A' },
  { question: 'In quale città ha sede il Milan?', optionA: 'Milano', optionB: 'Torino', correctAnswer: 'A' },
  { question: 'Quale squadra italiana gioca in rossonero?', optionA: 'Milan', optionB: 'Roma', correctAnswer: 'A' },
  { question: 'Quante squadre retrocedono dalla Serie A ogni anno?', optionA: 'Tre', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'Come si chiama il trofeo del campionato italiano?', optionA: 'Scudetto', optionB: 'Coppa Italia', correctAnswer: 'A' },
  { question: 'Chi ha vinto il Pallone d\'Oro italiano nel 2006?', optionA: 'Fabio Cannavaro', optionB: 'Gianluigi Buffon', correctAnswer: 'A' },
  { question: 'In quale anno è stata fondata la Juventus?', optionA: '1897', optionB: '1900', correctAnswer: 'A' },
  { question: 'Quale squadra è la rivale storica della Juventus?', optionA: 'Torino', optionB: 'Sampdoria', correctAnswer: 'A' },
  { question: 'Come si chiama il derby tra Milan e Inter?', optionA: 'Derby della Madonnina', optionB: 'Derby d\'Italia', correctAnswer: 'A' },
  { question: 'Quale squadra gioca in giallorosso?', optionA: 'Roma', optionB: 'Lecce', correctAnswer: 'A' },
  { question: 'In quale regione ha sede il Sassuolo?', optionA: 'Emilia-Romagna', optionB: 'Toscana', correctAnswer: 'A' },
  { question: 'Chi è stato il portiere della Juventus per vent\'anni?', optionA: 'Gianluigi Buffon', optionB: 'Dino Zoff', correctAnswer: 'A' },
  { question: 'Quale squadra italiana ha la sede a Bergamo?', optionA: 'Atalanta', optionB: 'Brescia', correctAnswer: 'A' },

  // --- CALCIO ESTERO ---
  { question: 'Quante volte ha vinto il Pallone d\'Oro Messi?', optionA: 'Otto', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'In quale paese gioca il Real Madrid?', optionA: 'Spagna', optionB: 'Portogallo', correctAnswer: 'A' },
  { question: 'Quale squadra ha vinto più Champions League?', optionA: 'Real Madrid', optionB: 'Barcelona', correctAnswer: 'A' },
  { question: 'In quale città si trova il Camp Nou?', optionA: 'Barcellona', optionB: 'Madrid', correctAnswer: 'A' },
  { question: 'Di quale nazionalità è Kylian Mbappé?', optionA: 'Francese', optionB: 'Belga', correctAnswer: 'A' },
  { question: 'Quale squadra inglese ha sede ad Anfield?', optionA: 'Liverpool', optionB: 'Everton', correctAnswer: 'A' },
  { question: 'In quale paese si disputa la Bundesliga?', optionA: 'Germania', optionB: 'Austria', correctAnswer: 'A' },
  { question: 'Chi è soprannominato "CR7"?', optionA: 'Cristiano Ronaldo', optionB: 'Carlos Roberto', correctAnswer: 'A' },
  { question: 'Quale squadra ha vinto il Mondiale 2022?', optionA: 'Argentina', optionB: 'Francia', correctAnswer: 'A' },
  { question: 'Di quale nazionalità è Erling Haaland?', optionA: 'Norvegese', optionB: 'Danese', correctAnswer: 'A' },
  { question: 'Quale squadra è chiamata "I Blancos"?', optionA: 'Real Madrid', optionB: 'Atletico Madrid', correctAnswer: 'A' },
  { question: 'Qual è il soprannome del Manchester United?', optionA: 'Red Devils', optionB: 'Red Army', correctAnswer: 'A' },
  { question: 'In quale paese si disputa la Ligue 1?', optionA: 'Francia', optionB: 'Belgio', correctAnswer: 'A' },
  { question: 'Quante stelle ha la maglia della nazionale brasiliana?', optionA: 'Cinque', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'In quale città ha sede il PSG?', optionA: 'Parigi', optionB: 'Lione', correctAnswer: 'A' },
  { question: 'Quale squadra spagnola ha il soprannome "Los Colchoneros"?', optionA: 'Atletico Madrid', optionB: 'Siviglia', correctAnswer: 'A' },
  { question: 'Chi è il bomber del Borussia Dortmund con la maglia gialla?', optionA: 'Haaland era lì prima', optionB: 'Lewandowski sempre lì', correctAnswer: 'A' },
  { question: 'In quale paese si gioca la Premier League?', optionA: 'Inghilterra', optionB: 'Scozia', correctAnswer: 'A' },
  { question: 'Quale squadra ha vinto la Copa America 2021?', optionA: 'Argentina', optionB: 'Brasile', correctAnswer: 'A' },
  { question: 'Come si chiama lo stadio del Bayern Monaco?', optionA: 'Allianz Arena', optionB: 'Signal Iduna Park', correctAnswer: 'A' },
  { question: 'Di quale paese è nazionale Luka Modric?', optionA: 'Croazia', optionB: 'Serbia', correctAnswer: 'A' },
  { question: 'Quale squadra olandese ha vinto la Champions League 1995?', optionA: 'Ajax', optionB: 'PSV', correctAnswer: 'A' },
  { question: 'In quale anno Zinedine Zidane ha ritirato per la testata a Materazzi?', optionA: '2006', optionB: '2002', correctAnswer: 'A' },
  { question: 'Quante coppe del Mondo ha vinto la Germania?', optionA: 'Quattro', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'Quale squadra inglese gioca a Old Trafford?', optionA: 'Manchester United', optionB: 'Manchester City', correctAnswer: 'A' },

  // --- SPORT IN GENERALE ---
  { question: 'In quale sport si usa il termine "ace"?', optionA: 'Tennis', optionB: 'Golf', correctAnswer: 'A' },
  { question: 'Quanti giocatori ci sono in una squadra di basket in campo?', optionA: 'Cinque', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'Che distanza si corre in una maratona?', optionA: '42,195 km', optionB: '40 km', correctAnswer: 'A' },
  { question: 'Quale atleta è considerato il più veloce della storia?', optionA: 'Usain Bolt', optionB: 'Carl Lewis', correctAnswer: 'A' },
  { question: 'In quale sport si usa la spada?', optionA: 'Scherma', optionB: 'Judo', correctAnswer: 'A' },
  { question: 'Quante basi ci sono nel baseball?', optionA: 'Quattro', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'In quale paese sono nate le Olimpiadi moderne?', optionA: 'Grecia', optionB: 'Francia', correctAnswer: 'A' },
  { question: 'Quanti anelli ha il simbolo olimpico?', optionA: 'Cinque', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'In quale sport si parla di "grande slam"?', optionA: 'Tennis', optionB: 'Golf', correctAnswer: 'A' },
  { question: 'Quanti round ha un match di boxe professionistico massimo?', optionA: 'Dodici', optionB: 'Quindici', correctAnswer: 'A' },
  { question: 'Chi ha vinto più titoli del Mondo di MotoGP?', optionA: 'Valentino Rossi', optionB: 'Marc Marquez', correctAnswer: 'A' },
  { question: 'In quale sport si usa il "birdie"?', optionA: 'Golf', optionB: 'Badminton', correctAnswer: 'A' },
  { question: 'Quanti giocatori ci sono in una squadra di rugby in campo?', optionA: 'Quindici', optionB: 'Tredici', correctAnswer: 'A' },
  { question: 'In quale sport si compete per il Trofeo Davis?', optionA: 'Tennis', optionB: 'Squash', correctAnswer: 'A' },
  { question: 'Quante medaglie d\'oro vale il primo posto alle Olimpiadi?', optionA: 'Una', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'In quale sport si usa il termine "strike"?', optionA: 'Bowling', optionB: 'Baseball', correctAnswer: 'A' },
  { question: 'Quale paese ha vinto più medaglie d\'oro olimpiche totali?', optionA: 'USA', optionB: 'Russia', correctAnswer: 'A' },
  { question: 'In quale sport si gareggia su una pista di ghiaccio ovale?', optionA: 'Pattinaggio di velocità', optionB: 'Curling', correctAnswer: 'A' },
  { question: 'Quanti punti vale una meta nel rugby?', optionA: 'Cinque', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'In quale sport si compete per la Coppa Ryder?', optionA: 'Golf', optionB: 'Tennis', correctAnswer: 'A' },
  { question: 'Quale paese ha vinto più volte la Coppa del Mondo di rugby?', optionA: 'Nuova Zelanda', optionB: 'Australia', correctAnswer: 'A' },
  { question: 'In quale sport si usa il termine "epee"?', optionA: 'Scherma', optionB: 'Judo', correctAnswer: 'A' },
  { question: 'Quante persone formano un team nella staffetta 4x100?', optionA: 'Quattro', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'In quale anno si sono tenute le Olimpiadi a Roma?', optionA: '1960', optionB: '1956', correctAnswer: 'A' },
  { question: 'Quale sport usa il termine "touchdown"?', optionA: 'Football americano', optionB: 'Rugby', correctAnswer: 'A' },

  // --- ANIMALI ---
  { question: 'Quante zampe ha un ragno?', optionA: 'Otto', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'Quale animale ha la gestazione più lunga?', optionA: 'Elefante', optionB: 'Balena', correctAnswer: 'A' },
  { question: 'Quante camere ha il cuore di un mammifero?', optionA: 'Quattro', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'Quale animale è il più veloce della terra?', optionA: 'Ghepardo', optionB: 'Leone', correctAnswer: 'A' },
  { question: 'Quante zampe ha un insetto?', optionA: 'Sei', optionB: 'Otto', correctAnswer: 'A' },
  { question: 'Quale animale è il più grande del mondo?', optionA: 'Balena Blu', optionB: 'Elefante africano', correctAnswer: 'A' },
  { question: 'Quale uccello non può volare?', optionA: 'Pinguino', optionB: 'Piccione', correctAnswer: 'A' },
  { question: 'Quale animale produce la seta?', optionA: 'Baco da seta', optionB: 'Ragno', correctAnswer: 'A' },
  { question: 'Quante gobbe ha il cammello battriano?', optionA: 'Due', optionB: 'Una', correctAnswer: 'A' },
  { question: 'Quale animale è il simbolo dell\'Australia?', optionA: 'Canguro', optionB: 'Koala', correctAnswer: 'A' },
  { question: 'In quale paese vive il panda gigante allo stato brado?', optionA: 'Cina', optionB: 'Giappone', correctAnswer: 'A' },
  { question: 'Quale animale è il più grande dei felini?', optionA: 'Tigre', optionB: 'Leone', correctAnswer: 'A' },
  { question: 'Quante dita ha normalmente un gatto su ogni zampa anteriore?', optionA: 'Cinque', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'Quale animale usa l\'ecolocalizzazione per navigare?', optionA: 'Pipistrello', optionB: 'Gufo', correctAnswer: 'A' },
  { question: 'Quale è il serpente più lungo del mondo?', optionA: 'Anaconda', optionB: 'Pitone reticolato', correctAnswer: 'A' },
  { question: 'Quanti anni può vivere una tartaruga gigante?', optionA: 'Oltre 150 anni', optionB: 'Circa 80 anni', correctAnswer: 'A' },
  { question: 'Quale animale è l\'unico mammifero che depone uova?', optionA: 'Ornitorinco', optionB: 'Echidna', correctAnswer: 'A' },
  { question: 'Quale uccello ha la maggiore apertura alare?', optionA: 'Albatross errante', optionB: 'Condor delle Ande', correctAnswer: 'A' },
  { question: 'Quanti stomaci ha una mucca?', optionA: 'Quattro', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'Quale animale produce il latte più ricco di grassi?', optionA: 'Foca', optionB: 'Mucca', correctAnswer: 'A' },
  { question: 'Quante ore dorme al giorno un koala mediamente?', optionA: '22', optionB: '16', correctAnswer: 'A' },
  { question: 'Quale animale ha il cervello più grande in proporzione al corpo?', optionA: 'Delfino', optionB: 'Scimpanzé', correctAnswer: 'A' },
  { question: 'Quale è il colore del sangue dei polpi?', optionA: 'Blu', optionB: 'Rosso', correctAnswer: 'A' },
  { question: 'Quale animale ha il becco più lungo in rapporto al corpo?', optionA: 'Colibrì spada', optionB: 'Tucano', correctAnswer: 'A' },
  { question: 'In quale continente vivono i lemuri allo stato brado?', optionA: 'Africa (Madagascar)', optionB: 'Asia', correctAnswer: 'A' },
  { question: 'Quale insetto è il più mortale al mondo?', optionA: 'Zanzara', optionB: 'Ape', correctAnswer: 'A' },
  { question: 'Quante specie di pinguini esistono circa?', optionA: '18', optionB: '8', correctAnswer: 'A' },
  { question: 'Quale animale ha il morso più forte tra i mammiferi terrestri?', optionA: 'Ippopotamo', optionB: 'Orso grizzly', correctAnswer: 'A' },

  // --- MUSICA ---
  { question: 'Quante corde ha un violino?', optionA: 'Quattro', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Di quale gruppo faceva parte Freddie Mercury?', optionA: 'Queen', optionB: 'Led Zeppelin', correctAnswer: 'A' },
  { question: 'In quale città è nato il jazz?', optionA: 'New Orleans', optionB: 'Chicago', correctAnswer: 'A' },
  { question: 'Quanti componenti avevano i Beatles?', optionA: 'Quattro', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'In quale anno si è tenuto il primo Festival di Sanremo?', optionA: '1951', optionB: '1960', correctAnswer: 'A' },
  { question: 'Quale strumento suonava Jimi Hendrix?', optionA: 'Chitarra', optionB: 'Basso', correctAnswer: 'A' },
  { question: 'Come si chiama la nota musicale che segue il "Sol"?', optionA: 'La', optionB: 'Si', correctAnswer: 'A' },
  { question: 'Quante note ha la scala musicale?', optionA: 'Sette', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Chi ha scritto "Bohemian Rhapsody"?', optionA: 'Freddie Mercury', optionB: 'Brian May', correctAnswer: 'A' },
  { question: 'Quale cantante italiano è soprannominato "il Blasco"?', optionA: 'Vasco Rossi', optionB: 'Ligabue', correctAnswer: 'A' },
  { question: 'In quale decennio è nato il rock and roll?', optionA: 'Anni 50', optionB: 'Anni 60', correctAnswer: 'A' },
  { question: 'Quale cantante si chiama Stefani Joanne Germanotta?', optionA: 'Lady Gaga', optionB: 'Katy Perry', correctAnswer: 'A' },
  { question: 'Quante corde ha un basso elettrico standard?', optionA: 'Quattro', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'In quale decennio i Beatles si sono sciolti?', optionA: 'Anni 70', optionB: 'Anni 80', correctAnswer: 'A' },
  { question: 'Quale strumento suona Elton John?', optionA: 'Pianoforte', optionB: 'Chitarra', correctAnswer: 'A' },
  { question: 'Quante ottave ha la voce umana media circa?', optionA: 'Tre', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Quale cantante pop ha pubblicato l\'album "Thriller"?', optionA: 'Michael Jackson', optionB: 'Prince', correctAnswer: 'A' },
  { question: 'In quale anno è morto Kurt Cobain?', optionA: '1994', optionB: '1991', correctAnswer: 'A' },
  { question: 'Quale gruppo musicale include Bono come cantante?', optionA: 'U2', optionB: 'Coldplay', correctAnswer: 'A' },
  { question: 'Quanti tasti ha un pianoforte standard?', optionA: '88', optionB: '76', correctAnswer: 'A' },
  { question: 'Quale cantante italiana ha vinto Sanremo con "Grande amore"?', optionA: 'Il Volo', optionB: 'Eros Ramazzotti', correctAnswer: 'A' },
  { question: 'In quale paese è nata la bossa nova?', optionA: 'Brasile', optionB: 'Argentina', correctAnswer: 'A' },
  { question: 'Quale strumento musicale ha la forma di un triangolo?', optionA: 'Triangolo', optionB: 'Arpa', correctAnswer: 'A' },
  { question: 'Chi è il cantante dei Coldplay?', optionA: 'Chris Martin', optionB: 'Thom Yorke', correctAnswer: 'A' },
  { question: 'Quante corde ha normalmente un arpa da concerto?', optionA: '47', optionB: '36', correctAnswer: 'A' },
  { question: 'Quale cantante italiana ha il soprannome "Patty"?', optionA: 'Patty Pravo', optionB: 'Patty Brard', correctAnswer: 'A' },
  { question: 'In quale nazione è nato Beethoven?', optionA: 'Germania', optionB: 'Austria', correctAnswer: 'A' },
  { question: 'Quale strumento è tipico della musica tradizionale scozzese?', optionA: 'Cornamusa', optionB: 'Violino', correctAnswer: 'A' },

  // --- GEOGRAFIA ---
  { question: 'Quale è il fiume più lungo del mondo?', optionA: 'Nilo', optionB: 'Amazzoni', correctAnswer: 'A' },
  { question: 'In quale continente si trova l\'Egitto?', optionA: 'Africa', optionB: 'Asia', correctAnswer: 'A' },
  { question: 'Quale è il lago più grande del mondo?', optionA: 'Mar Caspio', optionB: 'Lago Superiore', correctAnswer: 'A' },
  { question: 'Qual è la capitale del Brasile?', optionA: 'Brasilia', optionB: 'Rio de Janeiro', correctAnswer: 'A' },
  { question: 'In quale paese si trova il Taj Mahal?', optionA: 'India', optionB: 'Pakistan', correctAnswer: 'A' },
  { question: 'Qual è la capitale del Giappone?', optionA: 'Tokyo', optionB: 'Osaka', correctAnswer: 'A' },
  { question: 'Quale è il paese più piccolo del mondo?', optionA: 'Vaticano', optionB: 'Monaco', correctAnswer: 'A' },
  { question: 'In quale paese si trova il Machu Picchu?', optionA: 'Perù', optionB: 'Bolivia', correctAnswer: 'A' },
  { question: 'Quale è il mare più salato del mondo?', optionA: 'Mar Morto', optionB: 'Mar Rosso', correctAnswer: 'A' },
  { question: 'Qual è la capitale della Russia?', optionA: 'Mosca', optionB: 'San Pietroburgo', correctAnswer: 'A' },
  { question: 'In quale oceano si trovano Hawaii?', optionA: 'Pacifico', optionB: 'Atlantico', correctAnswer: 'A' },
  { question: 'Qual è la capitale dell\'Argentina?', optionA: 'Buenos Aires', optionB: 'Santiago', correctAnswer: 'A' },
  { question: 'Quale è il deserto più grande del mondo?', optionA: 'Sahara', optionB: 'Gobi', correctAnswer: 'A' },
  { question: 'In quale paese si trova la Grande Muraglia?', optionA: 'Cina', optionB: 'Mongolia', correctAnswer: 'A' },
  { question: 'Qual è il continente più piccolo?', optionA: 'Oceania', optionB: 'Europa', correctAnswer: 'A' },
  { question: 'Quale è la capitale dell\'Australia?', optionA: 'Canberra', optionB: 'Sydney', correctAnswer: 'A' },
  { question: 'In quale paese si trova il Kilimanjaro?', optionA: 'Tanzania', optionB: 'Kenya', correctAnswer: 'A' },
  { question: 'Quale è la capitale del Canada?', optionA: 'Ottawa', optionB: 'Toronto', correctAnswer: 'A' },
  { question: 'In quale paese si trova Amsterdam?', optionA: 'Paesi Bassi', optionB: 'Belgio', correctAnswer: 'A' },
  { question: 'Qual è la capitale della Spagna?', optionA: 'Madrid', optionB: 'Barcellona', correctAnswer: 'A' },
  { question: 'Quale è il paese africano con la popolazione più alta?', optionA: 'Nigeria', optionB: 'Etiopia', correctAnswer: 'A' },
  { question: 'In quale continente si trova il Messico?', optionA: 'America del Nord', optionB: 'America del Sud', correctAnswer: 'A' },
  { question: 'Quale è la capitale della Norvegia?', optionA: 'Oslo', optionB: 'Stoccolma', correctAnswer: 'A' },
  { question: 'In quale paese si trova Dublino?', optionA: 'Irlanda', optionB: 'Scozia', correctAnswer: 'A' },
  { question: 'Quale è il paese con il maggior numero di laghi?', optionA: 'Canada', optionB: 'Finlandia', correctAnswer: 'A' },
  { question: 'Quale è la catena montuosa più lunga del mondo?', optionA: 'Ande', optionB: 'Himalaya', correctAnswer: 'A' },
  { question: 'In quale paese si trova Atene?', optionA: 'Grecia', optionB: 'Turchia', correctAnswer: 'A' },
  { question: 'Quale è la capitale del Portogallo?', optionA: 'Lisbona', optionB: 'Porto', correctAnswer: 'A' },

  // --- STORIA ---
  { question: 'In quale anno è caduto il Muro di Berlino?', optionA: '1989', optionB: '1991', correctAnswer: 'A' },
  { question: 'Chi era il primo uomo sulla Luna?', optionA: 'Neil Armstrong', optionB: 'Buzz Aldrin', correctAnswer: 'A' },
  { question: 'In quale anno è iniziata la Prima Guerra Mondiale?', optionA: '1914', optionB: '1916', correctAnswer: 'A' },
  { question: 'In quale anno Cristoforo Colombo ha scoperto l\'America?', optionA: '1492', optionB: '1498', correctAnswer: 'A' },
  { question: 'Chi era il leader dell\'URSS durante la Seconda Guerra Mondiale?', optionA: 'Stalin', optionB: 'Lenin', correctAnswer: 'A' },
  { question: 'In quale anno è iniziata la Rivoluzione Francese?', optionA: '1789', optionB: '1776', correctAnswer: 'A' },
  { question: 'Quale imperatore romano ha costruito il Colosseo?', optionA: 'Vespasiano', optionB: 'Nerone', correctAnswer: 'A' },
  { question: 'In quale anno è stato assassinato JFK?', optionA: '1963', optionB: '1965', correctAnswer: 'A' },
  { question: 'Quale paese ha inventato la carta?', optionA: 'Cina', optionB: 'Egitto', correctAnswer: 'A' },
  { question: 'In quale anno è avvenuto lo sbarco in Normandia?', optionA: '1944', optionB: '1943', correctAnswer: 'A' },
  { question: 'Chi ha dipinto la Gioconda?', optionA: 'Leonardo da Vinci', optionB: 'Raffaello', correctAnswer: 'A' },
  { question: 'In quale anno è scoppiata la bomba atomica su Hiroshima?', optionA: '1945', optionB: '1944', correctAnswer: 'A' },
  { question: 'Chi era il faraone più famoso dell\'Egitto antico?', optionA: 'Ramses II', optionB: 'Tutankhamon', correctAnswer: 'A' },
  { question: 'In quale anno è stata fondata Roma secondo la leggenda?', optionA: '753 a.C.', optionB: '509 a.C.', correctAnswer: 'A' },
  { question: 'Chi ha sconfitto Napoleone a Waterloo?', optionA: 'Wellington', optionB: 'Blücher', correctAnswer: 'A' },
  { question: 'In quale anno ha abdicato l\'imperatore russo?', optionA: '1917', optionB: '1914', correctAnswer: 'A' },
  { question: 'Quale civiltà ha costruito le piramidi di Giza?', optionA: 'Egizi', optionB: 'Romani', correctAnswer: 'A' },
  { question: 'Chi era il comandante dell\'esercito romano Giulio Cesare?', optionA: 'Marco Antonio', optionB: 'Pompeo', correctAnswer: 'A' },
  { question: 'In quale anno è morto Alessandro Magno?', optionA: '323 a.C.', optionB: '356 a.C.', correctAnswer: 'A' },
  { question: 'Quale guerra iniziò con l\'assassinio dell\'arciduca Francesco Ferdinando?', optionA: 'Prima Guerra Mondiale', optionB: 'Seconda Guerra Mondiale', correctAnswer: 'A' },
  { question: 'Chi era il presidente degli USA durante la Seconda Guerra Mondiale?', optionA: 'Roosevelt', optionB: 'Truman', correctAnswer: 'A' },
  { question: 'In quale anno si è conclusa la guerra fredda?', optionA: '1991', optionB: '1989', correctAnswer: 'A' },
  { question: 'Quale rivoluzione è avvenuta in Russia nel 1917?', optionA: 'Rivoluzione d\'Ottobre', optionB: 'Rivoluzione di Febbraio', correctAnswer: 'A' },
  { question: 'Chi ha fondato l\'Impero mongolo?', optionA: 'Gengis Khan', optionB: 'Kublai Khan', correctAnswer: 'A' },
  { question: 'In quale città è stata firmata la Magna Carta nel 1215?', optionA: 'Runnymede', optionB: 'Londra', correctAnswer: 'A' },

  // --- MATEMATICA E SCIENZA ---
  { question: 'Quanto fa la radice quadrata di 144?', optionA: '12', optionB: '14', correctAnswer: 'A' },
  { question: 'Quanti lati ha un esagono?', optionA: 'Sei', optionB: 'Sette', correctAnswer: 'A' },
  { question: 'Qual è il numero pi greco approssimato?', optionA: '3,14', optionB: '3,41', correctAnswer: 'A' },
  { question: 'Quanto fa 15 x 15?', optionA: '225', optionB: '215', correctAnswer: 'A' },
  { question: 'Quanti angoli ha un triangolo?', optionA: 'Tre', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'A quanti gradi bolle l\'acqua al livello del mare?', optionA: '100', optionB: '90', correctAnswer: 'A' },
  { question: 'Quanti millilitri ha un litro?', optionA: '1000', optionB: '100', correctAnswer: 'A' },
  { question: 'Qual è il numero atomico dell\'idrogeno?', optionA: 'Uno', optionB: 'Due', correctAnswer: 'A' },
  { question: 'Quanto fa 2 elevato alla decima potenza?', optionA: '1024', optionB: '512', correctAnswer: 'A' },
  { question: 'Quanti lati ha un pentagono?', optionA: 'Cinque', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'Quanto fa la radice quadrata di 256?', optionA: '16', optionB: '14', correctAnswer: 'A' },
  { question: 'Qual è il simbolo chimico del sodio?', optionA: 'Na', optionB: 'So', correctAnswer: 'A' },
  { question: 'Quanti sono i numeri primi tra 1 e 10?', optionA: 'Quattro', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'Quanto fa 100 diviso 4?', optionA: '25', optionB: '20', correctAnswer: 'A' },
  { question: 'Qual è il simbolo chimico del ferro?', optionA: 'Fe', optionB: 'Fr', correctAnswer: 'A' },
  { question: 'Quanti gradi ci sono in un angolo retto?', optionA: '90', optionB: '180', correctAnswer: 'A' },
  { question: 'Cosa studia l\'astronomia?', optionA: 'Stelle e corpi celesti', optionB: 'L\'atmosfera', correctAnswer: 'A' },
  { question: 'Quanto fa 13 x 13?', optionA: '169', optionB: '179', correctAnswer: 'A' },
  { question: 'Qual è la formula della CO2?', optionA: 'Biossido di carbonio', optionB: 'Monossido di carbonio', correctAnswer: 'A' },
  { question: 'Quanti gradi ha la somma degli angoli di un triangolo?', optionA: '180', optionB: '360', correctAnswer: 'A' },
  { question: 'Quale è il numero primo più piccolo?', optionA: '2', optionB: '1', correctAnswer: 'A' },
  { question: 'Quanto fa 7 x 8?', optionA: '56', optionB: '54', correctAnswer: 'A' },
  { question: 'Quanti gradi ci sono in un angolo piatto?', optionA: '180', optionB: '90', correctAnswer: 'A' },
  { question: 'Qual è il simbolo chimico dell\'argento?', optionA: 'Ag', optionB: 'Ar', correctAnswer: 'A' },
  { question: 'Quanti elementi ha la tavola periodica moderna?', optionA: '118', optionB: '105', correctAnswer: 'A' },

  // --- MACCHINE E MOTO ---
  { question: 'In quale paese è nata la Ferrari?', optionA: 'Italia', optionB: 'Germania', correctAnswer: 'A' },
  { question: 'Quale pilota di F1 ha vinto più titoli mondiali?', optionA: 'Lewis Hamilton', optionB: 'Michael Schumacher', correctAnswer: 'A' },
  { question: 'Quanti cilindri ha tradizionalmente un motore V8?', optionA: 'Otto', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'In quale città ha sede la Ducati?', optionA: 'Bologna', optionB: 'Torino', correctAnswer: 'A' },
  { question: 'Quale marchio ha creato la Countach?', optionA: 'Lamborghini', optionB: 'Ferrari', correctAnswer: 'A' },
  { question: 'Chi è stato il primo campione del mondo di Formula 1?', optionA: 'Nino Farina', optionB: 'Juan Manuel Fangio', correctAnswer: 'A' },
  { question: 'Quale marchio produce la moto Ninja?', optionA: 'Kawasaki', optionB: 'Yamaha', correctAnswer: 'A' },
  { question: 'Di quale paese è originaria la Harley-Davidson?', optionA: 'USA', optionB: 'Canada', correctAnswer: 'A' },
  { question: 'Quale pilota è soprannominato "Il Dottore" in MotoGP?', optionA: 'Valentino Rossi', optionB: 'Max Biaggi', correctAnswer: 'A' },
  { question: 'In quale anno è stata fondata la Lamborghini?', optionA: '1963', optionB: '1955', correctAnswer: 'A' },
  { question: 'Quale marchio tedesco ha il logo con le quattro ruote?', optionA: 'Audi', optionB: 'BMW', correctAnswer: 'A' },
  { question: 'Quante ruote ha un sidecar?', optionA: 'Tre', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'Quale auto italiana è prodotta a Maranello?', optionA: 'Ferrari', optionB: 'Lamborghini', correctAnswer: 'A' },
  { question: 'In quale anno Michael Schumacher ha vinto il suo primo titolo di F1?', optionA: '1994', optionB: '1996', correctAnswer: 'A' },
  { question: 'Quale marchio produce la moto R1?', optionA: 'Yamaha', optionB: 'Honda', correctAnswer: 'A' },
  { question: 'Quante marce ha tipicamente un cambio manuale di un\'auto moderna?', optionA: 'Sei', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Quale è il paese più noto per la produzione di auto di lusso come Rolls-Royce?', optionA: 'Inghilterra', optionB: 'Germania', correctAnswer: 'A' },
  { question: 'Quale brand automobilistico usa il marchio del toro come logo?', optionA: 'Lamborghini', optionB: 'Ferrari', correctAnswer: 'A' },
  { question: 'In quale circuito si corre il Gran Premio di Monaco?', optionA: 'Monte Carlo', optionB: 'Monza', correctAnswer: 'A' },
  { question: 'Quale moto ha il modello "Panigale"?', optionA: 'Ducati', optionB: 'Aprilia', correctAnswer: 'A' },
  { question: 'Quale campione di F1 è soprannominato "Mad Max"?', optionA: 'Max Verstappen', optionB: 'Carlos Sainz', correctAnswer: 'A' },
  { question: 'In quale nazione è stata costruita la prima Ferrari?', optionA: 'Italia', optionB: 'Germania', correctAnswer: 'A' },
  { question: 'Quale marchio produce la Fiesta?', optionA: 'Ford', optionB: 'Fiat', correctAnswer: 'A' },
  { question: 'Quanti anni ci vogliono per far diventare Campione del Mondo di F1?', optionA: 'Una stagione', optionB: 'Almeno due stagioni', correctAnswer: 'A' },
  { question: 'Quale marchio giapponese produce la moto CBR?', optionA: 'Honda', optionB: 'Kawasaki', correctAnswer: 'A' },

  // --- DIVERTIMENTO FRA AMICI ---
  { question: 'Quante carte ha un mazzo di carte napoletane?', optionA: '40', optionB: '52', correctAnswer: 'A' },
  { question: 'Quale cocktail è fatto con prosecco e succo di pesca?', optionA: 'Bellini', optionB: 'Spritz', correctAnswer: 'A' },
  { question: 'In quale gioco si punta su numeri da 1 a 36?', optionA: 'Roulette', optionB: 'Craps', correctAnswer: 'A' },
  { question: 'Qual è la bevanda base dello Spritz veneziano?', optionA: 'Prosecco', optionB: 'Champagne', correctAnswer: 'A' },
  { question: 'In quale gioco da tavolo si conquista il mondo con le armate?', optionA: 'Risiko', optionB: 'Monopoly', correctAnswer: 'A' },
  { question: 'Quante carte si danno a testa nella Briscola?', optionA: 'Tre', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Quale piattaforma è famosa per i video brevi?', optionA: 'TikTok', optionB: 'Snapchat', correctAnswer: 'A' },
  { question: 'In che anno è stato fondato Facebook?', optionA: '2004', optionB: '2006', correctAnswer: 'A' },
  { question: 'Quante bowling pin ci sono in totale?', optionA: 'Dieci', optionB: 'Nove', correctAnswer: 'A' },
  { question: 'Quale gioco usa le parole "UNO!" quando si ha solo una carta?', optionA: 'Uno', optionB: 'Scala 40', correctAnswer: 'A' },
  { question: 'In quale gioco si gioca con pedine su una scacchiera di 64 caselle?', optionA: 'Scacchi', optionB: 'Dama', correctAnswer: 'A' },
  { question: 'Quante tessere ha un set completo di domino?', optionA: '28', optionB: '36', correctAnswer: 'A' },
  { question: 'In quale gioco si usa un coltello, un tubo di piombo e un candelabro?', optionA: 'Cluedo', optionB: 'Monopoly', correctAnswer: 'A' },
  { question: 'Quante facce ha un dado standard?', optionA: 'Sei', optionB: 'Otto', correctAnswer: 'A' },
  { question: 'Qual è il gioco di carte italiano dove si prende briscola?', optionA: 'Briscola', optionB: 'Scopa', correctAnswer: 'A' },
  { question: 'Quale social network ha il simbolo di un uccellino?', optionA: 'Twitter/X', optionB: 'TikTok', correctAnswer: 'A' },
  { question: 'In quale gioco si lancia una palla verso birilli?', optionA: 'Bowling', optionB: 'Bocce', correctAnswer: 'A' },
  { question: 'Qual è il gioco in cui si deve non far atterrare il palloncino per terra?', optionA: 'Palloncino', optionB: 'Pallavolo', correctAnswer: 'A' },
  { question: 'Quanti punti vale il jolly nel gioco del Ramino?', optionA: '0 (conta zero)', optionB: 'Venti', correctAnswer: 'A' },
  { question: 'In quale gioco da tavolo si comprano e vendono proprietà?', optionA: 'Monopoly', optionB: 'Risiko', correctAnswer: 'A' },
  { question: 'Quale app di messaggi usa un campanello come logo?', optionA: 'Telegram', optionB: 'Signal', correctAnswer: 'A' },
  { question: 'Quante lettere ha il termine "quiz"?', optionA: 'Quattro', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'In quale gioco si cerca di posizionare le X e le O in fila?', optionA: 'Tris', optionB: 'Quattro in fila', correctAnswer: 'A' },
  { question: 'Quanti giocatori giocano nella versione standard di burraco?', optionA: 'Quattro', optionB: 'Due', correctAnswer: 'A' },
  { question: 'In quale gioco bisogna costruire parole su una griglia?', optionA: 'Scarabeo', optionB: 'Taboo', correctAnswer: 'A' },
  { question: 'Quale è la piattaforma di streaming musicale più usata?', optionA: 'Spotify', optionB: 'Apple Music', correctAnswer: 'A' },
  { question: 'Quanti colori ha un cubo di Rubik standard?', optionA: 'Sei', optionB: 'Otto', correctAnswer: 'A' },
  { question: 'Quale gioco si gioca con palette su un tavolo verde?', optionA: 'Ping pong', optionB: 'Air hockey', correctAnswer: 'A' },

  // --- CINEMA E TELEVISIONE ---
  { question: 'Chi interpreta Iron Man nel MCU?', optionA: 'Robert Downey Jr.', optionB: 'Chris Evans', correctAnswer: 'A' },
  { question: 'In quale anno è uscito il primo film di Harry Potter?', optionA: '2001', optionB: '2000', correctAnswer: 'A' },
  { question: 'Quale attore interpreta James Bond nel film Casino Royale 2006?', optionA: 'Daniel Craig', optionB: 'Pierce Brosnan', correctAnswer: 'A' },
  { question: 'Chi ha diretto il film "Il Padrino"?', optionA: 'Francis Ford Coppola', optionB: 'Martin Scorsese', correctAnswer: 'A' },
  { question: 'Quanti film ha la saga principale di Star Wars?', optionA: 'Nove', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'In quale anno è uscito Titanic con DiCaprio?', optionA: '1997', optionB: '1999', correctAnswer: 'A' },
  { question: 'Quale attrice interpreta Hermione in Harry Potter?', optionA: 'Emma Watson', optionB: 'Emma Stone', correctAnswer: 'A' },
  { question: 'In quale serie TV appare il Trono di Spade?', optionA: 'Game of Thrones', optionB: 'Vikings', correctAnswer: 'A' },
  { question: 'Chi ha doppiato Simba adulto nel Re Leone originale?', optionA: 'Matthew Broderick', optionB: 'Jeremy Irons', correctAnswer: 'A' },
  { question: 'Quale film di Spielberg parla di dinosauri?', optionA: 'Jurassic Park', optionB: 'Indiana Jones', correctAnswer: 'A' },
  { question: 'In quale anno è uscito Avatar di James Cameron?', optionA: '2009', optionB: '2007', correctAnswer: 'A' },
  { question: 'Chi interpreta il Joker nel film del 2019?', optionA: 'Joaquin Phoenix', optionB: 'Heath Ledger', correctAnswer: 'A' },
  { question: 'Quale attore ha interpretato Forrest Gump?', optionA: 'Tom Hanks', optionB: 'Tom Cruise', correctAnswer: 'A' },
  { question: 'In quale anno è uscita la prima stagione di Stranger Things?', optionA: '2016', optionB: '2015', correctAnswer: 'A' },
  { question: 'Quale serie Netflix parla di spacciatori messicani?', optionA: 'Narcos Mexico', optionB: 'Breaking Bad', correctAnswer: 'A' },
  { question: 'Chi interpreta Spider-Man nel MCU?', optionA: 'Tom Holland', optionB: 'Andrew Garfield', correctAnswer: 'A' },
  { question: 'Quale film Disney parla di un pesce che cerca suo figlio?', optionA: 'Alla Ricerca di Nemo', optionB: 'Alla Ricerca di Dory', correctAnswer: 'A' },
  { question: 'Chi ha creato la serie Breaking Bad?', optionA: 'Vince Gilligan', optionB: 'David Chase', correctAnswer: 'A' },
  { question: 'Quale attore interpreta Batman nel film del 2022?', optionA: 'Robert Pattinson', optionB: 'Ben Affleck', correctAnswer: 'A' },
  { question: 'In quale anno è uscito Il Silenzio degli Innocenti?', optionA: '1991', optionB: '1989', correctAnswer: 'A' },
  { question: 'Quale film ha vinto l\'Oscar come miglior film nel 2020?', optionA: 'Parasite', optionB: '1917', correctAnswer: 'A' },
  { question: 'Chi interpreta Tony Soprano nella serie I Soprano?', optionA: 'James Gandolfini', optionB: 'Joe Pesci', correctAnswer: 'A' },
  { question: 'Quale attore è famoso per il ruolo di Achille in Troy?', optionA: 'Brad Pitt', optionB: 'Orlando Bloom', correctAnswer: 'A' },
  { question: 'In quale anno è uscita la prima stagione di The Crown?', optionA: '2016', optionB: '2018', correctAnswer: 'A' },
  { question: 'Quale film di Kubrick parla di astronauti?', optionA: '2001: Odissea nello Spazio', optionB: 'Shining', correctAnswer: 'A' },

  // --- CIBO E CUCINA ---
  { question: 'Quale pasta è tipica della cucina alla carbonara?', optionA: 'Spaghetti o rigatoni', optionB: 'Tagliatelle', correctAnswer: 'A' },
  { question: 'In quale regione italiana è nata la pizza?', optionA: 'Campania', optionB: 'Sicilia', correctAnswer: 'A' },
  { question: 'Quale formaggio si usa nel tiramisù?', optionA: 'Mascarpone', optionB: 'Ricotta', correctAnswer: 'A' },
  { question: 'Quale paese ha inventato la pasta?', optionA: 'Italia', optionB: 'Cina', correctAnswer: 'A' },
  { question: 'Quanti tipi di pasta ci sono in Italia secondo le stime?', optionA: 'Oltre 300', optionB: 'Circa 100', correctAnswer: 'A' },
  { question: 'Quale è il formaggio più prodotto al mondo?', optionA: 'Mozzarella', optionB: 'Cheddar', correctAnswer: 'A' },
  { question: 'In quale paese è nata la birra secondo la tradizione?', optionA: 'Mesopotamia antica', optionB: 'Germania', correctAnswer: 'A' },
  { question: 'Quale è il vino rosso più famoso del Piemonte?', optionA: 'Barolo', optionB: 'Chianti', correctAnswer: 'A' },
  { question: 'Quale frutto è il protagonista della crostata di fragole?', optionA: 'Fragola', optionB: 'Lampone', correctAnswer: 'A' },
  { question: 'Quale spezia arancione viene usata nel curry indiano?', optionA: 'Curcuma', optionB: 'Paprika', correctAnswer: 'A' },
  { question: 'In quale paese è nato il sushi?', optionA: 'Giappone', optionB: 'Cina', correctAnswer: 'A' },
  { question: 'Quale tipo di latte si usa nella mozzarella di bufala?', optionA: 'Bufala', optionB: 'Vacca', correctAnswer: 'A' },
  { question: 'Quale è la salsa di base per la pizza Margherita?', optionA: 'Pomodoro', optionB: 'Besciamella', correctAnswer: 'A' },
  { question: 'Quanti litri di latte servono per fare 1 kg di parmigiano?', optionA: 'Circa 14', optionB: 'Circa 5', correctAnswer: 'A' },
  { question: 'Quale cocktail è composto da vodka, succo di lime e birra allo zenzero?', optionA: 'Moscow Mule', optionB: 'Mojito', correctAnswer: 'A' },
  { question: 'Quale è il pane tipico della Sardegna?', optionA: 'Carasau', optionB: 'Ciabatta', correctAnswer: 'A' },
  { question: 'Quale pasta ha la forma di farfalla?', optionA: 'Farfalle', optionB: 'Conchiglie', correctAnswer: 'A' },
  { question: 'In quale regione italiana è nata la porchetta?', optionA: 'Lazio', optionB: 'Toscana', correctAnswer: 'A' },
  { question: 'Quale è il dolce tipico del Carnevale veneziano?', optionA: 'Frittelle', optionB: 'Cannoli', correctAnswer: 'A' },
  { question: 'Quale bevanda alcolica si ottiene distillando le vinacce?', optionA: 'Grappa', optionB: 'Sambuca', correctAnswer: 'A' },

  // --- TECNOLOGIA ---
  { question: 'Chi ha fondato Microsoft?', optionA: 'Bill Gates', optionB: 'Steve Jobs', correctAnswer: 'A' },
  { question: 'Quale sistema operativo usa il pinguino come logo?', optionA: 'Linux', optionB: 'Android', correctAnswer: 'A' },
  { question: 'In quale anno è stato lanciato il primo iPhone?', optionA: '2007', optionB: '2009', correctAnswer: 'A' },
  { question: 'Quale azienda ha creato il motore di ricerca Google?', optionA: 'Alphabet', optionB: 'Meta', correctAnswer: 'A' },
  { question: 'Quale è il linguaggio di programmazione più usato per il web front-end?', optionA: 'JavaScript', optionB: 'Python', correctAnswer: 'A' },
  { question: 'Quale social network ha il simbolo di una fotocamera?', optionA: 'Instagram', optionB: 'Pinterest', correctAnswer: 'A' },
  { question: 'In quale anno è stato creato il World Wide Web?', optionA: '1989', optionB: '1995', correctAnswer: 'A' },
  { question: 'Quanti bit ha un byte?', optionA: 'Otto', optionB: 'Sedici', correctAnswer: 'A' },
  { question: 'Quale azienda produce il chip A-series per iPhone?', optionA: 'Apple', optionB: 'Qualcomm', correctAnswer: 'A' },
  { question: 'Quale è il social network professionale più diffuso?', optionA: 'LinkedIn', optionB: 'Twitter', correctAnswer: 'A' },
  { question: 'In quale anno è nata Wikipedia?', optionA: '2001', optionB: '1998', correctAnswer: 'A' },
  { question: 'Quale azienda produce le console PlayStation?', optionA: 'Sony', optionB: 'Microsoft', correctAnswer: 'A' },
  { question: 'Quale linguaggio di programmazione è usato per l\'intelligenza artificiale?', optionA: 'Python', optionB: 'Java', correctAnswer: 'A' },
  { question: 'Quanti GB ci sono in 1 TB?', optionA: '1024', optionB: '1000', correctAnswer: 'A' },
  { question: 'Quale è il browser web più usato al mondo?', optionA: 'Google Chrome', optionB: 'Firefox', correctAnswer: 'A' },
  { question: 'Chi ha fondato Amazon?', optionA: 'Jeff Bezos', optionB: 'Elon Musk', correctAnswer: 'A' },
  { question: 'In quale anno è stato lanciato YouTube?', optionA: '2005', optionB: '2007', correctAnswer: 'A' },
  { question: 'Quale azienda ha creato Android?', optionA: 'Google', optionB: 'Samsung', correctAnswer: 'A' },
  { question: 'Cosa significa CPU in informatica?', optionA: 'Central Processing Unit', optionB: 'Computer Power Unit', correctAnswer: 'A' },
  { question: 'Quale azienda produce la console Xbox?', optionA: 'Microsoft', optionB: 'Sony', correctAnswer: 'A' },

  // --- ARTE E LETTERATURA ---
  { question: 'Chi ha scritto "I Promessi Sposi"?', optionA: 'Alessandro Manzoni', optionB: 'Giovanni Verga', correctAnswer: 'A' },
  { question: 'In quale anno è morto Michelangelo?', optionA: '1564', optionB: '1540', correctAnswer: 'A' },
  { question: 'Quale pittore spagnolo è noto per il cubismo?', optionA: 'Pablo Picasso', optionB: 'Salvador Dalì', correctAnswer: 'A' },
  { question: 'Chi ha scritto "Guerra e Pace"?', optionA: 'Tolstoy', optionB: 'Dostoevsky', correctAnswer: 'A' },
  { question: 'In quale museo si trova la Gioconda?', optionA: 'Louvre', optionB: 'Uffizi', correctAnswer: 'A' },
  { question: 'Chi ha scritto "Il Conte di Montecristo"?', optionA: 'Alexandre Dumas', optionB: 'Victor Hugo', correctAnswer: 'A' },
  { question: 'Quale pittore olandese ha tagliato il proprio orecchio?', optionA: 'Van Gogh', optionB: 'Rembrandt', correctAnswer: 'A' },
  { question: 'Chi ha scritto "Don Chisciotte"?', optionA: 'Cervantes', optionB: 'Lope de Vega', correctAnswer: 'A' },
  { question: 'In quale città italiana si trovano le Gallerie degli Uffizi?', optionA: 'Firenze', optionB: 'Roma', correctAnswer: 'A' },
  { question: 'Chi ha scritto "1984"?', optionA: 'George Orwell', optionB: 'Aldous Huxley', correctAnswer: 'A' },
  { question: 'Quale artista ha dipinto La persistenza della memoria?', optionA: 'Salvador Dalì', optionB: 'René Magritte', correctAnswer: 'A' },
  { question: 'Chi ha scritto "Il Signore degli Anelli"?', optionA: 'J.R.R. Tolkien', optionB: 'C.S. Lewis', correctAnswer: 'A' },
  { question: 'In quale anno è nato Leonardo da Vinci?', optionA: '1452', optionB: '1476', correctAnswer: 'A' },
  { question: 'Quale scrittore ha creato Sherlock Holmes?', optionA: 'Arthur Conan Doyle', optionB: 'Agatha Christie', correctAnswer: 'A' },
  { question: 'In quale stile artistico ha lavorato Claude Monet?', optionA: 'Impressionismo', optionB: 'Cubismo', correctAnswer: 'A' },

  // --- SCIENZA E NATURA ---
  { question: 'Quanti cromosomi ha una cellula umana normale?', optionA: '46', optionB: '42', correctAnswer: 'A' },
  { question: 'Quale è l\'organo più grande del corpo umano?', optionA: 'Pelle', optionB: 'Fegato', correctAnswer: 'A' },
  { question: 'In quale anno Darwin ha pubblicato L\'Origine delle Specie?', optionA: '1859', optionB: '1871', correctAnswer: 'A' },
  { question: 'Quanti anni ci ha messo la luce del sole a raggiungerci?', optionA: 'Circa 8 minuti', optionB: 'Circa 30 minuti', correctAnswer: 'A' },
  { question: 'Quale è l\'elemento più abbondante nell\'universo?', optionA: 'Idrogeno', optionB: 'Elio', correctAnswer: 'A' },
  { question: 'Quante vertebre ha la colonna vertebrale umana?', optionA: '33', optionB: '24', correctAnswer: 'A' },
  { question: 'Quale organo filtra il sangue?', optionA: 'Reni', optionB: 'Fegato', correctAnswer: 'A' },
  { question: 'In quale anno Einstein ha formulato la relatività ristretta?', optionA: '1905', optionB: '1915', correctAnswer: 'A' },
  { question: 'Quale è la temperatura corporea normale?', optionA: '37 gradi', optionB: '36 gradi', correctAnswer: 'A' },
  { question: 'Quanti milioni di anni fa si sono estinti i dinosauri?', optionA: '66 milioni', optionB: '100 milioni', correctAnswer: 'A' },
  { question: 'Quale pianeta ha più lune nel Sistema Solare?', optionA: 'Saturno', optionB: 'Giove', correctAnswer: 'A' },
  { question: 'Cosa studia la sismologia?', optionA: 'Terremoti', optionB: 'Vulcani', correctAnswer: 'A' },
  { question: 'Quale è il metallo più leggero?', optionA: 'Litio', optionB: 'Alluminio', correctAnswer: 'A' },
  { question: 'In quale strato dell\'atmosfera si trova l\'ozono?', optionA: 'Stratosfera', optionB: 'Troposfera', correctAnswer: 'A' },
  { question: 'Quante ossa ha il cranio umano adulto?', optionA: '22', optionB: '14', correctAnswer: 'A' },

  // --- FUMETTI E VIDEOGIOCHI ---
  { question: 'In quale videogame si combatte con una spada nella dimensione del Nether?', optionA: 'Minecraft', optionB: 'Terraria', correctAnswer: 'A' },
  { question: 'Quale personaggio Nintendo salta sui funghi?', optionA: 'Mario', optionB: 'Toad', correctAnswer: 'A' },
  { question: 'Chi è il villain principale di The Legend of Zelda?', optionA: 'Ganon', optionB: 'Vaati', correctAnswer: 'A' },
  { question: 'In quale gioco si costruiscono e gestiscono città?', optionA: 'Cities: Skylines', optionB: 'SimCity', correctAnswer: 'A' },
  { question: 'Quale fumetto Marvel parla di un ragazzo morso da un ragno?', optionA: 'Spider-Man', optionB: 'Ant-Man', correctAnswer: 'A' },
  { question: 'In quale videogame si guidano i kart su circuiti Nintendo?', optionA: 'Mario Kart', optionB: 'Crash Team Racing', correctAnswer: 'A' },
  { question: 'Quale personaggio DC Comics ha il mantello e il boomerang?', optionA: 'Batman', optionB: 'Superman', correctAnswer: 'A' },
  { question: 'In quale videogioco si costruiscono basi e si combatte in stile voxel?', optionA: 'Minecraft', optionB: 'Roblox', correctAnswer: 'A' },
  { question: 'Chi è il protagonista della serie di giochi Halo?', optionA: 'Master Chief', optionB: 'Marcus Fenix', correctAnswer: 'A' },
  { question: 'In quale gioco si affronta Bowser?', optionA: 'Super Mario', optionB: 'Donkey Kong', correctAnswer: 'A' },
  { question: 'Quale fumetto parla di mutanti con superpoteri guidati da Professor X?', optionA: 'X-Men', optionB: 'Avengers', correctAnswer: 'A' },
  { question: 'In quale videogame si usa un lazo per catturare animali?', optionA: 'Red Dead Redemption', optionB: 'Far Cry', correctAnswer: 'A' },
  { question: 'Quale personaggio Sega è famoso per la velocità?', optionA: 'Sonic', optionB: 'Tails', correctAnswer: 'A' },
  { question: 'Chi è il protagonista della serie Assassin\'s Creed originale?', optionA: 'Altair', optionB: 'Ezio', correctAnswer: 'A' },
  { question: 'In quale gioco si costruisce una fattoria e si allevano animali?', optionA: 'Stardew Valley', optionB: 'Harvest Moon', correctAnswer: 'A' },
]

export function getShuffledQuestions(count = 21): Question[] {
  return [...QUESTIONS]
    .sort(() => Math.random() - 0.5)
    .slice(0, count)
    .map(q => {
      if (Math.random() > 0.5) {
        return { ...q, optionA: q.optionB, optionB: q.optionA, correctAnswer: q.correctAnswer === 'A' ? 'B' : 'A' }
      }
      return q
    })
}
