import { Question } from './types'

export const QUESTIONS: Question[] = [
  { question: 'Qual è la capitale d\'Italia?', optionA: 'Roma', optionB: 'Milano', correctAnswer: 'A' },
  { question: 'Quanti giorni ha una settimana?', optionA: 'Sette', optionB: 'Otto', correctAnswer: 'A' },
  { question: 'Di che colore è il sole?', optionA: 'Giallo', optionB: 'Verde', correctAnswer: 'A' },
  { question: 'Quante zampe ha un gatto?', optionA: 'Quattro', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'L\'acqua bolle a quanti gradi Celsius?', optionA: '100', optionB: '50', correctAnswer: 'A' },
  { question: 'In quale continente si trova l\'Italia?', optionA: 'Europa', optionB: 'Africa', correctAnswer: 'A' },
  { question: 'Quale pianeta è il più vicino al Sole?', optionA: 'Mercurio', optionB: 'Venere', correctAnswer: 'A' },
  { question: 'Quante ore ha un giorno?', optionA: '24', optionB: '12', correctAnswer: 'A' },
  { question: 'Di che colore è il cielo sereno?', optionA: 'Blu', optionB: 'Rosso', correctAnswer: 'A' },
  { question: 'Qual è la moneta dell\'Italia?', optionA: 'Euro', optionB: 'Dollaro', correctAnswer: 'A' },
  { question: 'Quante settimane ha un anno?', optionA: '52', optionB: '30', correctAnswer: 'A' },
  { question: 'Quante corde ha una chitarra standard?', optionA: 'Sei', optionB: 'Quattro', correctAnswer: 'A' },
  { question: 'Quale animale fa "miao"?', optionA: 'Gatto', optionB: 'Cane', correctAnswer: 'A' },
  { question: 'Qual è il pianeta più grande del Sistema Solare?', optionA: 'Giove', optionB: 'Saturno', correctAnswer: 'A' },
  { question: 'Quante lettere ha l\'alfabeto italiano?', optionA: '21', optionB: '26', correctAnswer: 'A' },
  { question: 'In quale mese cade Natale?', optionA: 'Dicembre', optionB: 'Novembre', correctAnswer: 'A' },
  { question: 'Quale frutto è giallo e ricurvo?', optionA: 'Banana', optionB: 'Mela', correctAnswer: 'A' },
  { question: 'Quanti mesi ha un anno?', optionA: '12', optionB: '10', correctAnswer: 'A' },
  { question: 'Qual è l\'animale più grande del mondo?', optionA: 'Balena Blu', optionB: 'Elefante', correctAnswer: 'A' },
  { question: 'Dove si trova la Torre Eiffel?', optionA: 'Parigi', optionB: 'Londra', correctAnswer: 'A' },
  { question: 'Quanti continenti ha la Terra?', optionA: 'Sette', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Quale sport si gioca con un pallone rotondo su un campo erboso?', optionA: 'Calcio', optionB: 'Basket', correctAnswer: 'A' },
  { question: 'Di che colore è la neve?', optionA: 'Bianco', optionB: 'Grigio', correctAnswer: 'A' },
  { question: 'Quante dita ha una mano umana?', optionA: 'Cinque', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'Qual è la capitale della Francia?', optionA: 'Parigi', optionB: 'Lione', correctAnswer: 'A' },
  { question: 'Come si chiama il satellite naturale della Terra?', optionA: 'Luna', optionB: 'Sole', correctAnswer: 'A' },
  { question: 'Quante uova ha in genere una dozzina?', optionA: 'Dodici', optionB: 'Dieci', correctAnswer: 'A' },
  { question: 'Quale colore si ottiene mescolando rosso e blu?', optionA: 'Viola', optionB: 'Verde', correctAnswer: 'A' },
  { question: 'Quante ali ha una farfalla?', optionA: 'Quattro', optionB: 'Due', correctAnswer: 'A' },
  { question: 'In quale oceano si trova l\'Australia?', optionA: 'Pacifico', optionB: 'Atlantico', correctAnswer: 'A' },
  { question: 'Quale strumento suona Mozart?', optionA: 'Pianoforte', optionB: 'Chitarra', correctAnswer: 'A' },
  { question: 'Quante righe ha un foglio A4 standard non rigato?', optionA: 'Nessuna', optionB: 'Trenta', correctAnswer: 'A' },
  { question: 'Di che materiale è fatta la Statua della Libertà?', optionA: 'Rame', optionB: 'Oro', correctAnswer: 'A' },
  { question: 'Qual è la moneta del Giappone?', optionA: 'Yen', optionB: 'Won', correctAnswer: 'A' },
  { question: 'Quante zampe ha un ragno?', optionA: 'Otto', optionB: 'Sei', correctAnswer: 'A' },
  { question: 'In quale paese si trovano le Piramidi di Giza?', optionA: 'Egitto', optionB: 'Marocco', correctAnswer: 'A' },
  { question: 'Quale pianeta ha gli anelli più famosi?', optionA: 'Saturno', optionB: 'Urano', correctAnswer: 'A' },
  { question: 'Quanti secondi ha un minuto?', optionA: '60', optionB: '100', correctAnswer: 'A' },
  { question: 'Qual è la capitale della Germania?', optionA: 'Berlino', optionB: 'Monaco', correctAnswer: 'A' },
  { question: 'Quale animale è il simbolo dell\'Australia?', optionA: 'Canguro', optionB: 'Koala', correctAnswer: 'A' },
  { question: 'Quante note ha la scala musicale standard?', optionA: 'Sette', optionB: 'Cinque', correctAnswer: 'A' },
  { question: 'Di che colore è il mare?', optionA: 'Blu', optionB: 'Verde', correctAnswer: 'A' },
  { question: 'Quale ingrediente principale c\'è nella pizza Margherita?', optionA: 'Pomodoro', optionB: 'Pesto', correctAnswer: 'A' },
  { question: 'Quante volte al giorno si vede tramonto?', optionA: 'Una', optionB: 'Due', correctAnswer: 'A' },
  { question: 'Quale organo pompa il sangue nel corpo umano?', optionA: 'Cuore', optionB: 'Fegato', correctAnswer: 'A' },
  { question: 'Qual è il colore del latte?', optionA: 'Bianco', optionB: 'Giallo', correctAnswer: 'A' },
  { question: 'Dove si svolgono le Olimpiadi invernali?', optionA: 'In montagna', optionB: 'Al mare', correctAnswer: 'A' },
  { question: 'Quante zampe ha un insetto?', optionA: 'Sei', optionB: 'Otto', correctAnswer: 'A' },
  { question: 'Qual è il paese più popoloso del mondo?', optionA: 'India', optionB: 'USA', correctAnswer: 'A' },
  { question: 'Quante ruote ha una bicicletta?', optionA: 'Due', optionB: 'Tre', correctAnswer: 'A' },
  { question: 'Quale colore non è nell\'arcobaleno?', optionA: 'Rosa', optionB: 'Giallo', correctAnswer: 'A' },
  { question: 'Di che materiale è fatto il vetro?', optionA: 'Sabbia', optionB: 'Pietra', correctAnswer: 'A' },
  { question: 'Quante stelle ha la bandiera degli USA?', optionA: '50', optionB: '48', correctAnswer: 'A' },
  { question: 'In quale stagione cadono le foglie?', optionA: 'Autunno', optionB: 'Primavera', correctAnswer: 'A' },
  { question: 'Quanto fa 10 x 10?', optionA: '100', optionB: '110', correctAnswer: 'A' },
  { question: 'Quanti millimetri ci sono in un centimetro?', optionA: '10', optionB: '100', correctAnswer: 'A' },
  { question: 'Quale è il metallo più conduttore di calore?', optionA: 'Argento', optionB: 'Oro', correctAnswer: 'A' },
  { question: 'Quante zampe ha un cavallo?', optionA: 'Quattro', optionB: 'Due', correctAnswer: 'A' },
  { question: 'Qual è la capitale del Brasile?', optionA: 'Brasilia', optionB: 'Rio de Janeiro', correctAnswer: 'A' },
  { question: 'Quante pianeti ci sono nel Sistema Solare?', optionA: 'Otto', optionB: 'Nove', correctAnswer: 'A' },
  { question: 'Di che colore è l\'erba in primavera?', optionA: 'Verde', optionB: 'Giallo', correctAnswer: 'A' },
]

export function getShuffledQuestions(count = 21): Question[] {
  return [...QUESTIONS].sort(() => Math.random() - 0.5).slice(0, count)
}
