export const WORDS: string[] = [
  // --- CALCIO ITALIANO ---
  'Portiere','Rigore','Fuorigioco','Scudetto','Pallone','Corner','Fallo','Gol',
  'Arbitro','Stadio','Tifoso','Allenatore','Traversa','Palo','Serie A','Coppa Italia',
  'Dribbling','Assist','Centravanti','Terzino','Centrocampista','Capitano','Fascia',
  'Offside','Cartellino','Rosso','Giallo','Rimessa','Esultanza','Doppietta','Tripletta',
  'Juventus','Milan','Inter','Roma','Napoli','Lazio','Fiorentina','Atalanta','Torino',
  'Bologna','Sampdoria','Genoa','Parma','Cagliari','Udinese','Spezia','Salernitana',
  'Totti','Del Piero','Maldini','Buffon','Pirlo','Cannavaro','Baggio','Rivera',
  'Inzaghi','Baresi','Costacurta','Vialli','Mancini','Vieri','Signori','Shevchenko',
  'Curva','Derby','Ultras','Settore ospiti','Tifo','Fumogeno','Bandiera','Coro',
  'Panenka','Cucchiaio','Rovesciata','Tacco','Punizione','Barriera','Muro','Tap-in',
  'Portiere','VAR','Goal line technology','Sala VAR','Moviola','Fermo immagine',

  // --- CALCIO ESTERO ---
  'Messi','Ronaldo','Mbappé','Haaland','Neymar','Benzema','Lewandowski','Salah',
  'Modric','De Bruyne','Son','Vinicius','Bellingham','Pedri','Gavi','Yamal',
  'Real Madrid','Barcellona','Bayern Monaco','Manchester City','Liverpool','Arsenal',
  'Chelsea','PSG','Atletico Madrid','Dortmund','Ajax','Porto','Benfica','Sporting',
  'Tottenham','Newcastle','Aston Villa','Manchester United','Leicester','West Ham',
  'Siviglia','Valencia','Villarreal','Betis','Real Sociedad','Athletic Bilbao',
  'Premier League','Bundesliga','Liga','Ligue 1','Champions League','Europa League',
  'Conference League','Copa America','Mondiale','Europeo','Pallone d\'Oro','Scarpa d\'Oro',
  'Wembley','San Siro','Bernabeu','Camp Nou','Old Trafford','Maracana','Azteca',
  'Anfield','Etihad','Stamford Bridge','Signal Iduna Park','Allianz Arena',

  // --- SPORT ---
  'Tennis','Nuoto','Ciclismo','Atletica','Boxe','Rugby','Pallavolo','Basket',
  'Baseball','Golf','Sci','Snowboard','Pattinaggio','Scherma','Canottaggio',
  'Equitazione','Tiro con l\'arco','Lotta','Judo','Karate','Taekwondo','Aikido',
  'Ping pong','Badminton','Pallamano','Hockey','Pallanuoto','Triathlon','Pentathlon',
  'Biathlon','Skeleton','Bob','Curling','Salto con gli sci','Combinata nordica',
  'Olimpiadi','Podio','Medaglia','Oro','Argento','Bronzo','Cronometro','Staffetta',
  'Maratona','Sprint','Decathlon','Eptathlon','Marcia','Salto in alto','Salto in lungo',
  'Lancio del disco','Lancio del giavellotto','Lancio del martello','Peso',
  'Federer','Nadal','Djokovic','Sinner','Alcaraz','Swiatek','Williams','Graf',
  'Bolt','Phelps','Indurain','Pantani','Cipollini','Contador','Nibali','Vingegaard',
  'Formula 1','MotoGP','Rally','Pit stop','Pole position','Giro veloce','Sorpasso',
  'Motocross','Superbike','Enduro','Sidecar','Quad','Trial','Karting','Dragster',
  'Surf','Kitesurf','Windsurf','Skate','Skateboard','Parkour','Freeride','Downhill',

  // --- ANIMALI ---
  'Giraffa','Gorilla','Cobra','Panda','Koala','Canguro','Leopardo','Ghepardo',
  'Rinoceronte','Ippopotamo','Pinguino','Delfino','Squalo','Polpo','Medusa',
  'Granchio','Tartaruga','Coccodrillo','Camaleonte','Fenicottero','Pavone',
  'Gufo','Aquila','Corvo','Pappagallo','Tucano','Pellicano','Orca','Beluga',
  'Balena','Narvalo','Platipus','Axolotl','Piranha','Anaconda','Mamba','Pitone',
  'Licaone','Iene','Sciacallo','Mangusta','Procione','Castoro','Lontra','Topo',
  'Volpe','Lupo','Orso','Alce','Bisonte','Zebra','Gnu','Antilope','Bufalo',
  'Lemure','Capibara','Armadillo','Bradipo','Formichiere','Tapiro','Peccari',
  'Struzzo','Emù','Kiwi','Albatros','Fenicottero','Marabù','Cicogna','Airone',
  'Salmone','Trota','Tonno','Pesce spada','Murena','Anguilla','Pesce palla',
  'Mantide religiosa','Scorpione','Tarantola','Libellula','Lucciola','Cavalletta',
  'Scarabeo','Farfalla monarca','Ape regina','Calabrone','Zanzara tigre','Mosca tsé-tsé',
  'Meerkat','Lemure dagli occhi grossi','Pangolino','Okapi','Fossa','Kinkajou',
  'Axolotl','Ornitorinco','Echidna','Quokka','Numbat','Wombat','Tasmanian devil',

  // --- MUSICA ---
  'Chitarra','Pianoforte','Batteria','Violino','Sassofono','Tromba','Flauto',
  'Microfono','Concerto','Album','Singolo','Discoteca','DJ','Rap','Rock',
  'Jazz','Pop','Opera','Coro','Spartito','Amplificatore','Basso','Tastiera',
  'Arpa','Oboe','Clarinetto','Tuba','Trombone','Corno','Fagotto','Contrabasso',
  'Ukulele','Mandolino','Banjo','Fisarmonica','Organetto','Cornamusa','Sitar',
  'Accordo','Ritornello','Strofa','Bridge','Ritmo','Melodia','Armonia','Tempo',
  'Freddie Mercury','Elvis Presley','Michael Jackson','Beatles','Rolling Stones',
  'David Bowie','Madonna','Beyoncé','Eminem','Bob Dylan','Jimi Hendrix','Janis Joplin',
  'Nirvana','Pearl Jam','Radiohead','Coldplay','U2','Metallica','AC/DC','Pink Floyd',
  'Vasco Rossi','Ligabue','Zucchero','Laura Pausini','Tiziano Ferro','Eros Ramazzotti',
  'Lucio Battisti','Fabrizio De André','Lucio Dalla','Pino Daniele','Ivan Graziani',
  'Festival di Sanremo','Tour','Backstage','Bis','Ovazione','Bis','Encore',
  'Hip hop','R&B','Soul','Funk','Reggae','Ska','Punk','Heavy metal','Grunge',
  'Elettronica','House','Techno','Trance','Drum and bass','Dubstep','Trap',

  // --- MACCHINE E MOTO ---
  'Ferrari','Lamborghini','Porsche','BMW','Mercedes','Audi','Volkswagen',
  'Toyota','Tesla','Maserati','Alfa Romeo','Fiat','Bugatti','McLaren','Aston Martin',
  'Rolls Royce','Bentley','Jaguar','Land Rover','Range Rover','Volvo','Saab',
  'Ford','Chevrolet','Dodge','Jeep','Chrysler','Cadillac','Lincoln','Buick',
  'Nissan','Honda','Subaru','Mazda','Mitsubishi','Hyundai','Kia','Suzuki',
  'Schumacher','Senna','Hamilton','Verstappen','Leclerc','Vettel','Alonso','Prost',
  'Ducati','Yamaha','Honda','Kawasaki','Harley Davidson','Aprilia','Suzuki','KTM',
  'Valentino Rossi','Marquez','Quartararo','Bagnaia','Dovizioso','Pedrosa',
  'Motore','Carburatore','Turbo','Frizione','Marcia','Sterzo','Cofano','Carrozzeria',
  'Pneumatico','Cerchio','Freno','Scarico','Serbatoio','Cruscotto','Abitacolo',
  'Formula 1','MotoGP','Rally','DTM','NASCAR','IndyCar','Le Mans','Dakar',
  'Pit stop','Pole position','Safety car','Virtual safety car','Penalità',
  'Hypercar','Supercar','Berlina','SUV','Crossover','Cabriolet','Coupé','Station wagon',

  // --- GEOGRAFIA ---
  'Himalaya','Amazzonia','Sahara','Antartide','Artico','Vesuvio','Etna','Stromboli',
  'Nilo','Tamigi','Mississippi','Amazzoni','Yangtze','Gange','Volga','Danubio',
  'Adriatico','Mediterraneo','Atlantico','Pacifico','Indiano','Artico','Antartico',
  'Tokyo','New York','Londra','Parigi','Berlino','Sydney','Dubai','Mumbai',
  'Rio de Janeiro','Buenos Aires','Città del Messico','Pechino','Mosca','Cairo',
  'Cape Town','Lagos','Nairobi','Addis Abeba','Kinshasa','Casablanca',
  'Singapore','Bangkok','Kuala Lumpur','Giacarta','Manila','Seoul','Taipei',
  'Alpi','Dolomiti','Appennini','Andes','Rockies','Kilimanjaro','Everest','K2',
  'Sicilia','Sardegna','Corsica','Islanda','Madagascar','Groenlandia','Tasmania',
  'Borneo','Sumatra','Giava','Hokkaido','Okinawa','Sri Lanka','Cipro','Malta',
  'Sahel','Savana','Tundra','Taiga','Permafrost','Delta','Estuario','Fiordo',
  'Atollo','Arcipelago','Penisola','Istmo','Promontorio','Pianura Padana','Po',
  'Lago di Garda','Lago Maggiore','Lago di Como','Lago Trasimeno','Lago d\'Iseo',
  'Geyser','Canyon','Mesa','Falesia','Scogliera','Spiaggia bianca','Laguna',

  // --- STORIA ---
  'Gladiatore','Faraone','Vikingo','Cavaliere','Castello','Colosseo','Piramide',
  'Pirati','Samurai','Ninja','Legionario','Centurione','Imperatore','Sultano',
  'Napoleone','Alessandro Magno','Giulio Cesare','Cleopatra','Leonardo da Vinci',
  'Colombo','Magellano','Copernico','Galileo','Newton','Darwin','Einstein','Curie',
  'Rivoluzione Francese','Rivoluzione Industriale','Prima Guerra Mondiale',
  'Seconda Guerra Mondiale','Guerra Fredda','Muro di Berlino','Sbarco sulla Luna',
  'Rinascimento','Medioevo','Illuminismo','Barocco','Romanticismo','Modernismo',
  'Crociata','Inquisizione','Peste nera','Scoperta dell\'America','Riforma protestante',
  'Rivoluzione americana','Dichiarazione d\'indipendenza','Costituzione americana',
  'Bismarck','Churchill','De Gaulle','Roosevelt','Stalin','Hitler','Mussolini',
  'Gandhi','Mandela','Luther King','Che Guevara','Fidel Castro','Mao Zedong',
  'Cleopatra','Nefertiti','Boudicca','Giovanna d\'Arco','Maria Antonietta',
  'Tempio greco','Anfiteatro','Acquedotto','Arco di trionfo','Foro romano',
  'Spada','Scudo','Armatura','Elmo','Arco e frecce','Catapulta','Ariete',

  // --- CIBO E CUCINA ---
  'Lasagna','Carbonara','Risotto','Tiramisù','Cannolo','Gelato','Sushi',
  'Hamburger','Tacos','Croissant','Baguette','Spaghetti','Ravioli','Pesto',
  'Bruschetta','Arancino','Cannelloni','Gnocchi','Polenta','Ossobuco',
  'Steak','Salmone','Tonno','Aragosta','Tartufo','Parmigiano','Mozzarella',
  'Prosciutto','Salame','Mortadella','Caprese','Minestrone','Ribollita','Caponata',
  'Espresso','Cappuccino','Macchiato','Caffè latte','Tè','Mojito','Spritz','Negroni',
  'Ramen','Pad thai','Pho','Bibimbap','Gyoza','Tempura','Tonkatsu','Yakitori',
  'Paella','Tortilla','Gazpacho','Churros','Croquetas','Jamón','Sangria',
  'Fish and chips','Pudding','Scones','Haggis','Full english breakfast',
  'Baguette','Croissant','Crêpe','Ratatouille','Quiche','Soufflé','Crème brûlée',
  'Bratwurst','Pretzel','Sauerkraut','Schnitzel','Strudel','Bier','Glühwein',
  'Sushi','Sashimi','Tempura','Miso','Edamame','Takoyaki','Okonomiyaki',
  'Guacamole','Nachos','Enchilada','Burrito','Quesadilla','Margarita',

  // --- CINEMA E TV ---
  'Tarantino','Spielberg','Kubrick','Fellini','Scorsese','Nolan','Fincher','Coppola',
  'Oscar','Cannes','Venezia','Berlino','Golden Globe','BAFTA','Emmy','Grammy',
  'Titanic','Avatar','Avengers','Batman','Superman','Spiderman','Star Wars','Matrix',
  'Hobbit','Harry Potter','James Bond','Indiana Jones','Jurassic Park','Terminator',
  'Pulp Fiction','Shining','Psycho','Citizen Kane','Casablanca','Schindler\'s List',
  'Il padrino','C\'era una volta in America','Nuovo cinema paradiso','La vita è bella',
  'Netflix','Prime Video','Disney Plus','HBO','Hulu','Apple TV','Peacock',
  'Pixar','Marvel','DC','Universal','Paramount','Warner Bros','Sony','20th Century',
  'Stranger Things','Game of Thrones','Breaking Bad','The Office','Friends','Seinfeld',
  'Squid Game','La casa di carta','Peaky Blinders','Dark','Suburra','Gomorra',
  'Homer Simpson','Walter White','Tony Soprano','Don Draper','Daenerys','Jon Snow',

  // --- TECNOLOGIA ---
  'iPhone','Android','Samsung','Apple','Google','Microsoft','Amazon','Meta',
  'Intelligenza artificiale','ChatGPT','Cloud','Big data','Blockchain','Metaverso',
  'Computer','Laptop','Tablet','Smartphone','Smartwatch','Cuffie wireless',
  'Instagram','TikTok','Twitter','YouTube','Facebook','LinkedIn','Pinterest','Snapchat',
  'Bitcoin','Ethereum','NFT','Criptovaluta','Mining','Wallet','Exchange',
  'Wi-Fi','Bluetooth','4G','5G','Fibra ottica','Satellite','GPS','VPN',
  'Cybersecurity','Hacker','Virus','Firewall','Antivirus','Phishing','Ransomware',
  'Robot','Drone','Stampante 3D','Realtà virtuale','Realtà aumentata','Ologramma',
  'Tesla','SpaceX','Falcon 9','Starship','Stazione spaziale','Hubble','James Webb',

  // --- ARTE E LETTERATURA ---
  'Michelangelo','Leonardo','Raffaello','Caravaggio','Tiziano','Botticelli',
  'Van Gogh','Picasso','Monet','Dalì','Warhol','Banksy','Frida Kahlo','Klimt',
  'Mona Lisa','Ultima Cena','Creazione di Adamo','Notte stellata','Girasoli',
  'Guernica','Urlo di Munch','Ninfee','Persistenza della memoria','Pop art',
  'Dante','Petrarca','Boccaccio','Ariosto','Tasso','Manzoni','Verga','D\'Annunzio',
  'Shakespeare','Cervantes','Tolstoj','Dostoevskij','Kafka','Proust','Joyce',
  'Orwell','Hemingway','Fitzgerald','Faulkner','Woolf','Dickens','Jane Austen',
  'Harry Potter','Signore degli Anelli','Narnia','Don Chisciotte','Odissea','Iliade',
  'Romanzo','Poesia','Teatro','Commedia','Tragedia','Novella','Racconto','Saggio',

  // --- CORPO UMANO ---
  'Cuore','Polmone','Fegato','Rene','Cervello','Stomaco','Pancreas','Milza',
  'Osso','Muscolo','Tendine','Cartilagine','Legamento','Nervo','Vena','Arteria',
  'DNA','Cromosoma','Gene','Proteina','Vitamina','Ormone','Anticorpo','Enzima',
  'Globulo rosso','Globulo bianco','Piastrina','Plasma','Emoglobina',
  'Pupilla','Retina','Timpano','Papilla gustativa','Recettore','Sinapsi',

  // --- NATURA E PIANTE ---
  'Quercia','Faggio','Abete','Pino','Olivo','Cipresso','Palma','Bambù','Sequoia',
  'Rosa','Tulipano','Girasole','Orchidea','Lavanda','Cactus','Felce','Muschio',
  'Fotosintesi','Clorofilla','Radice','Stelo','Foglia','Fiore','Seme','Frutto',
  'Ecosistema','Foresta pluviale','Mangrovie','Prateria','Savana','Tundra','Taiga',
  'Vulcano','Terremoto','Tsunami','Uragano','Tornado','Grandine','Nebbia',
  'Arcobaleno','Aurora boreale','Eclipse','Meteora','Cometa','Asteroide',

  // --- FUMETTI E VIDEOGIOCHI ---
  'Superman','Batman','Spider-Man','Iron Man','Thor','Capitan America','Hulk',
  'Wonder Woman','Black Widow','Black Panther','Doctor Strange','Ant-Man',
  'Topolino','Paperino','Pluto','Pippo','Zio Paperone','Gambadilegno',
  'Asterix','Obelix','Getafix','Panoramix','Abraracourcix','Cacofonix',
  'Mario','Luigi','Peach','Bowser','Yoshi','Donkey Kong','Link','Zelda','Ganon',
  'Pikachu','Charizard','Mewtwo','Gengar','Snorlax','Eevee','Jigglypuff',
  'Sonic','Tails','Knuckles','Eggman','Shadow','Amy Rose','Silver',
  'Master Chief','Lara Croft','Nathan Drake','Kratos','Geralt','Aloy','Ellie',
  'Minecraft','Fortnite','FIFA','Call of Duty','GTA','Red Dead','Cyberpunk',
  'Pac-Man','Tetris','Space Invaders','Donkey Kong','Pong','Galaga',

  // --- PROFESSIONI ---
  'Medico','Chirurgo','Infermiere','Dentista','Veterinario','Farmacista',
  'Avvocato','Giudice','Notaio','Procuratore','Detective','Poliziotto',
  'Pompiere','Paramedico','Lifeguard','Guardia del corpo','Militare',
  'Architetto','Ingegnere','Geometra','Urbanista','Designer','Grafico',
  'Chef','Sommelier','Pasticcere','Pizzaiolo','Barista','Cameriere',
  'Pilota','Astronauta','Marinaio','Capitano','Macchinista','Controllore',
  'Maestro','Professore','Preside','Pedagogista','Psicologo','Counselor',
  'Giornalista','Fotografo','Cameraman','Regista','Sceneggiatore','Attore',

  // --- OGGETTI DI CASA ---
  'Frigorifero','Lavastoviglie','Lavatrice','Asciugatrice','Forno','Microonde',
  'Aspirapolvere','Robot aspirapolvere','Ferro da stiro','Tostapane',
  'Divano','Poltrona','Amaca','Cuscino','Coperta','Lenzuolo','Piumone',
  'Specchio','Quadro','Poster','Pianta','Lampada','Lampadario','Candela',
  'Scaffale','Libreria','Cassettone','Armadio','Comodino','Cassapanca',

  // --- PAESI E CAPITALI ---
  'Italia','Germania','Francia','Spagna','Portogallo','Polonia','Romania',
  'Svezia','Norvegia','Finlandia','Danimarca','Olanda','Belgio','Svizzera',
  'Austria','Grecia','Turchia','Russia','Ucraina','Ungheria','Repubblica Ceca',
  'Brasile','Argentina','Cile','Colombia','Perù','Venezuela','Ecuador',
  'Stati Uniti','Canada','Messico','Cuba','Giamaica','Panama','Costa Rica',
  'Giappone','Cina','India','Indonesia','Corea del Sud','Vietnam','Thailandia',
  'Egitto','Marocco','Nigeria','Kenya','Sudafrica','Etiopia','Tanzania',

  // --- DIVERTIMENTO E VITA SOCIALE ---
  'Karaoke','Briscola','Scopa','Tressette','Monopoly','Risiko','Scarabeo',
  'Poker','Blackjack','Dadi','Frisbee','Bowling','Biliardo','Freccette',
  'Escape room','Paintball','Karting','Laser tag','Go-kart','Trampoline park',
  'Aperitivo','Brindisi','Compleanno','Sorpresa','Confetti','Coriandoli',
  'Selfie','Influencer','Meme','Viral','Like','Follower','Story','Reel',
  'Vacanza','Spiaggia','Ombrellone','Sdraio','Piscina','Waterpark','Campeggio',
  'Capodanno','Halloween','Carnevale','Pasqua','Natale','San Valentino',
  'Zanzara','Sonnellino','Russare','Dieta','Palestra','Divano','Telecomando',
  'Hangover','Pipì di notte','Foto imbarazzante','Gruppo WhatsApp','Spam',

  // --- METEO E NATURA ---
  'Temporale','Arcobaleno','Nebbia','Grandine','Neve','Ghiaccio','Vento',
  'Uragano','Tifone','Tornado','Ciclone','Alluvione','Valanga','Frana',
  'Siccità','Caldo record','Ondata di calore','Gelo','Tormenta','Nevischio',
  'Estate','Inverno','Autunno','Primavera','Equinozio','Solstizio',
  'Eclissi','Aurora boreale','Arcobaleno doppio','Fulmine','Tuono',

  // --- SPORT ESTREMI E AVVENTURA ---
  'Paracadutismo','Bungee jumping','Base jumping','Wingsuit','Slacklining',
  'Arrampicata','Via ferrata','Alpinismo','Trekking','Orienteering',
  'Rafting','Kayak','Canoa','Windsurf','Kitesurf','Wakeboard','Wakeskate',
  'BMX','Mountain bike','Downhill','Freeride','Dirt jump','Trials',
  'Immersione','Snorkeling','Apnea','Speleo','Caving','Zip line',

  // --- MITOLOGIA E RELIGIONE ---
  'Zeus','Poseidone','Apollo','Atena','Afrodite','Ares','Ercole','Achille',
  'Odisseo','Minotauro','Medusa','Ciclope','Sirena','Sfinge','Chimera',
  'Thor','Odino','Loki','Valkiria','Ragnarok','Valhalla','Asgard',
  'Faraone','Ra','Anubi','Osiride','Iside','Horus','Sfinge','Sarcofago',
  'Drago','Unicorno','Fenice','Grifone','Pegaso','Centauro','Manticora',
]

export function getShuffledWords(): string[] {
  return [...WORDS].sort(() => Math.random() - 0.5)
}
